# 1 IMPORT LIBRARY

In [74]:
import pandas as pd
import numpy as np
import os
import sys
import subprocess
import time
from datetime import datetime, timedelta
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

In [75]:
folder_path = "O:\\Shared drives\\VEMP Supply Planning\\Projects\\MRP Transformation\\MRP_BOM_Central_official\\"

In [ ]:
con = snowflake.connector.connect(

)
cur = con.cursor()

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://sso.colpal.com/app/snowflake/exk5d2wdao1LeZ8Vr357/sso/saml?SAMLRequest=pZNLb%2BIwFIX%2FSuRZJ04CpcUCqvBqI4VCS4pmujOJAQvHTn0dQv99HR6jzqLdzM6yz%2FF37z127%2F5YCOfANHAl%2ByjwfOQwmamcy20fvaZT9w45YKjMqVCS9dEHA3Q%2F6AEtREmiyuzkC3uvGBjHXiSBNAd9VGlJFAUORNKCATEZWUazhISeTygA08bi0MWSA7esnTElwbiua69ueUpvcej7Pva72KoayS%2F0BVH%2BzCi1MipT4mo52p6%2BQQTYbzcIq7CExcU45PI8gp8o67MIyGOaLtzFfJkiJ7p2N1ISqoLpJdMHnrHXl%2BRcANgKRvPkIUoniyiZzZN4NRlPVl4Fbsak0VQE3jYrPZCq3gi6Z5kqyspYjmdXeMNyLNSW2%2BnF4z4q9zxvP08el6PqmT51dlU6G%2B43sVk%2BmD9r2k1%2Fd8P37HA7pWJVDdfbDDmra9Zhk3UMULFYNgkbu%2BWHLTfw3bCT%2BgFpdUi76wXt7htyxjZhLqk5Oa9tAChbkyipOJVGyxL%2FrRqz4%2F4mD%2BucqiBhb3cr3bq5bRy4iQ%2BdXxA54fXg%2F%2BfSw1%2FvuzzPJ5tYPF4owbMPZ6p0Qc33gQZecNrhubs5SQkrKBdRnmsGYIMVQtUjzaixv8DoiiE8OFP%2F%2FQeDTw%3D%3D&RelayState=65384 to authenticate...

# 2 DOWNLOAD ZMNU

In [77]:
# subprocess.check_call(['C:\Program Files (x86)\SAP\FrontEnd\SAPgui\\sapshcut.exe', '-system=CAP', '-client=321', '-user=USERNAME', '-pw=PASSWORD'])
# time.sleep(20)
# print ('Done')

In [78]:
# vbs_path = folder_path + "zmnu_bom_all_level.vbs"
# subprocess.call(['cscript.exe', vbs_path])
# print ('Done ZMNU')

# 3 TRANSFORM ZMNU INTO BOMTREE

## 3.1 READ ZMNU

In [79]:
df= pd.read_csv(folder_path+"BOM_All_Level_do_not_delete.xls",sep= "\t",encoding="utf-16",skiprows=3,usecols=list(range(1,20)))

df = df[~df['Material'].isnull()]
df = df[~df['Material'].str.startswith('CMK')]

column_mapping = {
    df.columns[4]: 'Component Quantity',
    df.columns[8]: 'Material Quantity',
    df.columns[5]: 'Component UOM',
    df.columns[10]: 'Material UOM'
}

df = df.rename(columns=column_mapping)
df.columns = df.columns.str.strip()

# Get recycle material
df_recycle = df[df['Material'].str.match(r'^M\d{5}$')].copy()

# Filter BOM status 1
df = df[(df["BOM Sts"] == 1) & (~df["Material"].str.match(r'^M\d{5}$'))]

# Filter out CmpValidFr > year 2100
df = df[df['CmpValidFr'].str[-4:].astype(int) < 2100]

# Get material code data
df_pair = df.iloc[:, [0, 2]].copy()
df_pair = df_pair.drop_duplicates()

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11606 entries, 0 to 29661
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Material               11606 non-null  object
 1   Material Description   11606 non-null  object
 2   Component              11606 non-null  object
 3   Component Description  11606 non-null  object
 4   Component Quantity     11606 non-null  object
 5   Component UOM          11606 non-null  object
 6   AltBOM                 11606 non-null  object
 7   BOM Sts                11606 non-null  int64
 8   Material Quantity      11606 non-null  object
 9   Item                   11606 non-null  object
 10  Material UOM           11606 non-null  object
 11  Change no.             4367 non-null   float64
 12  chng no. to            1164 non-null   float64
 13  OpScrap%               11606 non-null  float64
 14  cmpScrap%              11606 non-null  float64
 15  BOM Usg                11606 non-null  int64
 16  Valid Form             11606 non-null  object
 17  CmpValidFr             11606 non-null  object
 18  cmpValidTo             11606 non-null  object
dtypes: float64(4), int64(2), object(13)
memory usage: 1.8+ MB

## 3.2 EXTRACT ECN CHANGE

In [81]:
df_ecn = df[['Material','Component','Change no.','chng no. to','CmpValidFr','cmpValidTo']].copy()
df_ecn['Change no.'] = df_ecn['Change no.'].astype(str)
df_ecn['Change no.'] = df_ecn['Change no.'].str.rstrip('.0')
df_ecn['chng no. to'] = df_ecn['chng no. to'].astype(str)
df_ecn['chng no. to'] = df_ecn['chng no. to'].str.rstrip('.0')
df_ecn.head()

  Material    Component Change no. chng no. to  CmpValidFr  cmpValidTo
0    31371  C0000000934        nan         nan  05/25/2016  12/31/9999
1    31371    P11230075        nan         nan  05/25/2016  12/31/9999
2    31372  C0000001016        nan         nan  05/25/2016  12/31/9999
3    31372    P11230075        nan         nan  05/25/2016  12/31/9999
4    31373  C0000001017        nan         nan  05/25/2016  12/31/9999

In [82]:
# Calculate today - 1 day
one_day_ago = datetime.now() - timedelta(days=1)
one_day_ago_str = one_day_ago.strftime('%m/%d/%Y')
one_day_ago_dt = datetime.strptime(one_day_ago_str, '%m/%d/%Y')

In [83]:
# Filter the DataFrame based on string comparison
df_ecn_filtered_temp = df_ecn[
    df_ecn['cmpValidTo'].apply(lambda x: datetime.strptime(x, '%m/%d/%Y')) >= one_day_ago_dt
]
df_ecn_filtered_temp = df_ecn_filtered_temp[df_ecn_filtered_temp['cmpValidTo'].str[-4] < '3000']
#filtered_df = filtered_df[~filtered_df['cmpValidTo'].str[-4].eq('9999')]
df_ecn_filtered_temp = df_ecn_filtered_temp[df_ecn_filtered_temp['chng no. to']!='nan']

ECN_no = df_ecn_filtered_temp['chng no. to'].unique()
ECN_no

array(['500000028368', '500000028679', '500000028369', '50000002868',
       '500000028681', '500000027084', '500000028682', '500000028683',
       '500000028684', '500000028685', '500000028686', '500000028687',
       '500000028688', '500000028689', '500000027092', '50000002706',
       '500000027061', '500000027062', '500000027058', '500000027059',
       '50000002869', '500000028691', '500000027065', '500000027064',
       '500000027093', '500000028364', '500000028365', '500000029074',
       '500000028366', '500000028367', '50000002837', '500000028371',
       '500000028372', '500000028374', '500000028693', '500000028694',
       '500000028695', '500000028696', '500000028375', '500000028697',
       '500000028314', '500000027063', '500000028698', '500000028699',
       '5000000287', '500000027069', '500000027095', '500000028702',
       '500000028703', '500000028704', '500000028705', '500000028706',
       '50000002707', '500000027072', '500000027073', '500000028378',
       '500000027071', '500000028707', '500000028708', '500000028709',
       '50000002871', '500000028711', '500000027088', '500000027074',
       '500000028712', '500000028713', '500000028714', '500000028925',
       '500000028379', '50000002838', '500000027075', '500000027077',
       '50000002885', '500000027076', '500000029312', '500000029311',
       '500000027089', '500000028715', '500000028716', '500000028717',
       '500000026282', '500000028718', '500000028852', '500000028381',
       '500000028719', '50000002872', '500000028721', '500000027078',
       '500000028722', '500000027091', '500000028723', '500000027079',
       '500000028724', '50000002708', '50000002775', '500000027081',
       '500000027082', '500000027083', '500000027842', '500000028382',
       '500000028383', '500000027751', '500000028384', '500000028385',
       '500000027844', '500000027921', '500000028386', '500000028725',
       '500000027096', '500000028726', '500000028727', '500000028728',
       '500000028729', '50000002873', '500000028387', '500000028731',
       '500000028388', '500000028732', '500000028733', '500000028734',
       '500000029313', '500000028735', '500000028389', '500000028736',
       '500000028737', '500000029318', '500000028738', '500000028739',
       '500000029314', '50000002874', '500000028741', '500000028742',
       '500000029323', '500000028743', '500000028744', '500000028745',
       '500000028746', '500000028747', '500000029315', '500000028748',
       '500000028749', '50000002875', '500000028751', '500000028752',
       '500000028753', '500000028754', '500000028755', '500000027085',
       '500000027086', '500000027087', '500000028756', '50000002709',
       '500000029317', '50000002822', '500000028757', '500000028911',
       '500000028758', '500000028774', '50000002839', '50000002878',
       '500000028781', '500000028912', '500000028782', '500000028783',
       '500000028784', '500000028785', '500000028786', '50000002891',
       '500000028787', '500000028788', '500000028221', '500000028789',
       '500000027879', '50000002879', '500000028391', '500000028791',
       '500000028392', '500000028792', '500000028656', '500000028877',
       '50000002932', '500000029316', '500000028793', '500000028393',
       '500000028794', '500000028795', '500000028796', '500000028797',
       '500000028798', '500000028799', '500000029202', '50000002831',
       '500000028311', '5000000288', '500000028801', '500000028802',
       '500000028803', '500000028804', '500000028805', '500000028806',
       '500000028376', '500000028807', '500000028377', '500000028808',
       '500000028809', '500000028373', '50000002881', '500000028394',
       '500000028811', '500000029324', '500000028812', '500000027067',
       '500000027066', '500000029325', '500000028663', '500000028813',
       '500000028814', '500000028815', '500000027094', '500000011611',
       '500000028816', '500000028817', '500000028818', '500000029321',
       '500000029322', '500000028819', '500000028395', '500000027068',
       '50000002882', '500000029326', '500000028821', '500000028822'],
      dtype=object)

In [84]:
# Create a boolean mask for rows where 'Change no.' or 'chng no. to' is in ECN_no
mask = (df_ecn['Change no.'].isin(ECN_no)) | (df_ecn['chng no. to'].isin(ECN_no))

# Apply the mask to the DataFrame to filter rows
df_ecn_filtered = df_ecn[mask]
df_ecn_filtered

,Material,Component,Change no.,chng no. to,CmpValidFr,cmpValidTo
326,312272,C0000005899,nan,500000028368,03/10/2023,04/17/2024
327,312272,C0000010544,500000028368,nan,04/17/2024,12/31/9999
328,312272,C0000005900,nan,500000028368,03/10/2023,04/17/2024
329,312272,C0000010545,500000028368,nan,04/17/2024,12/31/9999
330,312272,C0000005901,nan,500000028368,03/10/2023,04/17/2024
...,...,...,...,...,...,...
29323,VN01129A,C0000010371,500000029326,nan,11/26/2023,12/31/9999
29327,VN01129A,P11270110,nan,500000028821,02/14/2019,10/27/2023
29328,VN01129A,P11270195,500000028821,nan,10/27/2023,12/31/9999
29460,VN01267A,P11270110,500000016876,500000028822,10/23/2018,10/27/2023
29461,VN01267A,P11270195,500000028822,nan,10/27/2023,12/31/9999

In [85]:
# Replace "nan" strings with actual NaN values
df_ecn_filtered.replace('nan', np.nan, inplace=True)

# Create dictionaries to store Component values for matching Change no. and chng no. to
change_to_component = {}
chng_to_change = {}

# Create a dictionary to store the "New Material" values in the original order
new_material_dict = {}

# Function to create the "New/old Material" column
def create_new_material(row):
    new_material = []

    if not pd.isna(row['Change no.']):
        change_no = row['Change no.']
        
        matching_rows = df_ecn_filtered[df_ecn_filtered['chng no. to'] == change_no]
        if not matching_rows.empty:
            components = matching_rows['Component'].tolist()
            if len(components) > 1:
                new_material.extend(components)
            elif len(components) == 1:
                new_material.append(components[0])

    if not pd.isna(row['chng no. to']):
        chng_no_to = row['chng no. to']
        
        matching_rows = df_ecn_filtered[df_ecn_filtered['Change no.'] == chng_no_to]
        if not matching_rows.empty:
            components = matching_rows['Component'].tolist()
            if len(components) > 1:
                new_material.extend(components)
            elif len(components) == 1:
                new_material.append(components[0])

    if new_material:
        new_material_dict[row.name] = ' - '.join(new_material)
        return ' - '.join(new_material)
    else:
        return row['Component']

# Apply the function to create the new column
df_ecn_filtered['New/old Material'] = df_ecn_filtered.apply(create_new_material, axis=1)

# Reorder the "New Material" column based on the original order
df_ecn_filtered.loc[:, 'New/old Material'] = df_ecn_filtered.index.map(new_material_dict)

df_ecn_filtered

C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\1100895899.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ecn_filtered.replace('nan', np.nan, inplace=True)
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\1100895899.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ecn_filtered['New/old Material'] = df_ecn_filtered.apply(create_new_material, axis=1)
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\1100895899.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ecn_filtered.loc[:, 'New/old Material'] = df_ecn_filtered.index.map(new_material_dict)

,Material,Component,Change no.,chng no. to,CmpValidFr,cmpValidTo,New/old Material
326,312272,C0000005899,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
327,312272,C0000010544,500000028368,NaN,04/17/2024,12/31/9999,C0000005899 - C0000005900 - C0000005901 - C000...
328,312272,C0000005900,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
329,312272,C0000010545,500000028368,NaN,04/17/2024,12/31/9999,C0000005899 - C0000005900 - C0000005901 - C000...
330,312272,C0000005901,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
...,...,...,...,...,...,...,...
29323,VN01129A,C0000010371,500000029326,NaN,11/26/2023,12/31/9999,C0000005930 - C0000005931 - C0000005932 - C000...
29327,VN01129A,P11270110,NaN,500000028821,02/14/2019,10/27/2023,P11270195
29328,VN01129A,P11270195,500000028821,NaN,10/27/2023,12/31/9999,P11270110
29460,VN01267A,P11270110,500000016876,500000028822,10/23/2018,10/27/2023,P11270195
29461,VN01267A,P11270195,500000028822,NaN,10/27/2023,12/31/9999,P11270110

## 3.3 CREATE BOMTREE

In [86]:
# Convert data to a list of tuples
list_pair = list(df_pair.itertuples(index=False, name=None))
list_pair

[('31371', 'C0000000934'),
 ('31371', 'P11230075'),
 ('31372', 'C0000001016'),
 ('31372', 'P11230075'),
 ('31373', 'C0000001017'),
 ('31373', 'P11230075'),
 ('31375', 'C0000001018'),
 ('31375', 'P11230075'),
 ('31377', 'C0000002130'),
 ('31377', 'P11230082'),
 ('31380', 'C0000002485'),
 ('31380', 'P11230086'),
 ('31381', 'C0000002486'),
 ('31381', 'P11230086'),
 ('31382', 'C0000002487'),
 ('31382', 'P11230086'),
 ('31387', 'C0000003540'),
 ('31387', 'P11230086'),
 ('31388', 'C0000003790'),
 ('31388', 'P11230082'),
 ('31390', 'C0000003791'),
 ('31390', 'P11230082'),
 ('31392', 'C0000003792'),
 ('31392', 'P11230082'),
 ('31394', 'C0000003793'),
 ('31394', 'P11230082'),
 ('31452', 'C0000005691'),
 ('31452', 'P11230082'),
 ('31454', 'C0000005692'),
 ('31454', 'P11230082'),
 ('31455', 'C0000005693'),
 ('31455', 'P11230082'),
 ('31463', 'C0000003537'),
 ('31463', 'P11230082'),
 ('31464', 'C0000003538'),
 ('31464', 'P11230082'),
 ('31465', 'C0000003539'),
 ('31465', 'P11230082'),
 ('31511', 'C0000004023'),
 ('31511', 'P11230082'),
 ('31512', 'C0000004024'),
 ('31512', 'P11230082'),
 ('31513', 'C0000004025'),
 ('31513', 'P11230082'),
 ('31514', 'C0000004026'),
 ('31514', 'P11230082'),
 ('31660', 'C0000006612'),
 ('31660', 'P11230082'),
 ('31661', 'C0000006611'),
 ('31661', 'P11230082'),
 ('31662', 'C0000006610'),
 ('31662', 'P11230082'),
 ('31663', 'C0000006609'),
 ('31663', 'P11230082'),
 ('31664', 'C0000005155'),
 ('31664', 'P11230086'),
 ('31665', 'C0000005156'),
 ('31665', 'P11230086'),
 ('31666', 'C0000005157'),
 ('31666', 'P11230086'),
 ('31667', 'C0000005158'),
 ('31667', 'P11230086'),
 ('31668', 'C0000005895'),
 ('31668', 'P11230086'),
 ('31669', 'C0000005896'),
 ('31669', 'P11230086'),
 ('31670', 'C0000005897'),
 ('31670', 'P11230086'),
 ('31671', 'C0000005898'),
 ('31671', 'P11230086'),
 ('31672', 'C0000005899'),
 ('31672', 'P11230086'),
 ('31673', 'C0000005900'),
 ('31673', 'P11230086'),
 ('31674', 'C0000005901'),
 ('31674', 'P11230086'),
 ('31675', 'C0000005902'),
 ('31675', 'P11230086'),
 ('31676', 'C0000005202'),
 ('31676', 'P11230086'),
 ('31677', 'C0000005203'),
 ('31677', 'P11230086'),
 ('31678', 'C0000005204'),
 ('31678', 'P11230086'),
 ('31679', 'C0000005205'),
 ('31679', 'P11230086'),
 ('31680', 'C0000005829'),
 ('31680', 'P11230086'),
 ('31681', 'C0000005830'),
 ('31681', 'P11230086'),
 ('31682', 'C0000005831'),
 ('31682', 'P11230086'),
 ('31683', 'C0000005974'),
 ('31683', 'P11230086'),
 ('31684', 'C0000005148'),
 ('31684', 'P11230086'),
 ('31685', 'C0000005149'),
 ('31685', 'P11230086'),
 ('31686', 'C0000005150'),
 ('31686', 'P11230086'),
 ('31687', 'C0000005151'),
 ('31687', 'P11230086'),
 ('31688', 'C0000007110'),
 ('31688', 'P11230086'),
 ('31689', 'C0000007109'),
 ('31689', 'P11230086'),
 ('31690', 'C0000007108'),
 ('31690', 'P11230086'),
 ('31860', 'C0000005134'),
 ('31860', 'P11230055'),
 ('31883', 'C0000005136'),
 ('31883', 'P11230055'),
 ('31994', 'C0000008395'),
 ('31994', 'P11230094'),
 ('31995', 'C0000008393'),
 ('31995', 'P11230094'),
 ('31996', 'C0000008394'),
 ('31996', 'P11230094'),
 ('31997', 'C0000008392'),
 ('31997', 'P11230094'),
 ('31998', 'C0000008404'),
 ('31998', 'P11230094'),
 ('31999', 'C0000008402'),
 ('31999', 'P11230094'),
 ('32000', 'C0000007871'),
 ('32000', 'P11230086'),
 ('32002', 'C0000007874'),
 ('32002', 'P11230086'),
 ('32003', 'C0000007873'),
 ('32003', 'P11230086'),
 ('32004', 'C0000007872'),
 ('32004', 'P11230086'),
 ('32010', 'C0000008403'),
 ('32010', 'P11230094'),
 ('32011', 'C0000008401'),
 ('32011', 'P11230094'),
 ('32023', 'C0000007526'),
 ('32023', 'P11212035'),
 ('32023', 'P11220273'),
 ('32024', 'C0000007527'),
 ('32024', 'P11212035'),
 ('32024', 'P11220273'),
 ('32026', 'C0000007528'),
 ('32026', 'P11212035'),
 ('32026', 'P11220273'),
 ('32027', 'C0000007529'),
 ('32027', 'P11212035'),
 ('32027', 'P11220273'),
 ('32028', 'C0000005631'),
 ('32028', 'P11212034'),
 ('32028', 'P11220273'),
 ('32029', 'C0000005632'),
 ('32029', 'P11212034'),
 ('32029', 'P11220273'),
 ('32040', 'C0000005633'),
 ('32040', 'P11212034'),
 ('32040', 'P11220273'),
 ('32041', 'C0000005634'),
 ('32041', 'P11212034'),
 ('32041', 'P11220273'),
 ('32103', 'C0000008965'),
 ('32103', 'P11230082'),
 ('32104', 'C0000008966'),
 ('32104', 'P11230082'),
 ('32105', 'C0000008967'),
 ('32105', 'P11230082'),
 ('32106', 'C0000008968'),
 ('32106', 'P11230082'),
 ('32130', 'C0000009119'),
 ('32130', 'P11230082'),
 ('32131', 'C0000009118'),
 ('32131', 'P11230082'),
 ('32132', 'C0000009117'),
 ('32132', 'P11230082'),
 ('32133', 'C0000009116'),
 ('32133', 'P11230082'),
 ('32135', 'C0000009123'),
 ('32135', 'P11230082'),
 ('32136', 'C0000009122'),
 ('32136', 'P11230082'),
 ('32137', 'C0000009121'),
 ('32137', 'P11230082'),
 ('32138', 'C0000009120'),
 ('32138', 'P11230082'),
 ('32152', 'C0000009123'),
 ('32153', 'C0000009122'),
 ('32154', 'C0000009120'),
 ('32155', 'C0000009121'),
 ('32232', 'C0000009477'),
 ('32232', 'P11230094'),
 ('32233', 'C0000009476'),
 ('32233', 'P11230094'),
 ('32234', 'C0000009474'),
 ('32234', 'P11230094'),
 ('32235', 'C0000009475'),
 ('32235', 'P11230094'),
 ('32236', 'C0000009481'),
 ('32236', 'P11230094'),
 ('32237', 'C0000009478'),
 ('32237', 'P11230094'),
 ('32238', 'C0000009479'),
 ('32238', 'P11230094'),
 ('32239', 'C0000009480'),
 ('32239', 'P11230094'),
 ('32252', 'C0000009576'),
 ('32252', 'P11230086'),
 ('32253', 'C0000009577'),
 ('32253', 'P11230086'),
 ('32254', 'C0000009578'),
 ('32254', 'P11230086'),
 ('32320', 'C0000010294'),
 ('32320', 'P11230086'),
 ('32321', 'C0000010293'),
 ('32321', 'P11230086'),
 ('32322', 'C0000010291'),
 ('32322', 'P11230086'),
 ('32323', 'C0000010292'),
 ('32323', 'P11230086'),
 ('32342', 'C0000010392'),
 ('32342', 'P11230094'),
 ('32343', 'C0000010391'),
 ('32343', 'P11230094'),
 ('32344', 'C0000010389'),
 ('32344', 'P11230094'),
 ('32345', 'C0000010390'),
 ('32345', 'P11230094'),
 ('32346', 'C0000010388'),
 ('32346', 'P11230094'),
 ('32347', 'C0000010385'),
 ('32347', 'P11230094'),
 ('32348', 'C0000010386'),
 ('32348', 'P11230094'),
 ('32349', 'C0000010387'),
 ('32349', 'P11230094'),
 ('32371', 'C0000008958'),
 ('32371', 'P11230082'),
 ('32372', 'C0000008959'),
 ('32372', 'P11230082'),
 ('32373', 'C0000008960'),
 ('32373', 'P11230082'),
 ('32374', 'C0000008961'),
 ('32374', 'P11230082'),
 ('32380', 'C0000010481'),
 ('32380', 'P11230082'),
 ('32381', 'C0000010480'),
 ('32381', 'P11230082'),
 ('32382', 'C0000010479'),
 ('32382', 'P11230082'),
 ('32383', 'C0000010478'),
 ('32383', 'P11230082'),
 ('32400', 'C0000010548'),
 ('32400', 'P11230086'),
 ('32401', 'C0000010549'),
 ('32401', 'P11230086'),
 ('32402', 'C0000010550'),
 ('32402', 'P11230086'),
 ('32403', 'C0000010551'),
 ('32403', 'P11230086'),
 ('32404', 'C0000010544'),
 ('32404', 'P11230086'),
 ('32405', 'C0000010545'),
 ('32405', 'P11230086'),
 ('32406', 'C0000010546'),
 ('32406', 'P11230086'),
 ('32407', 'C0000010547'),
 ('32407', 'P11230086'),
 ('32420', 'C0000009845'),
 ('32420', 'P11230086'),
 ('32421', 'C0000009846'),
 ('32421', 'P11230086'),
 ('32422', 'C0000009847'),
 ('32422', 'P11230086'),
 ('32423', 'C0000009848'),
 ('32423', 'P11230086'),
 ('168742', 'C0000010010'),
 ('168742', 'C0000010011'),
 ('168742', 'C0000010012'),
 ('168742', 'C0000010013'),
 ('168743', 'C0000010019'),
 ('168743', 'C0000010020'),
 ('168743', 'C0000010021'),
 ('168743', 'C0000010022'),
 ('168768', 'C0000010278'),
 ('168768', 'C0000010279'),
 ('168768', 'C0000010280'),
 ('312272', 'C0000005899'),
 ('312272', 'C0000010544'),
 ('312272', 'C0000005900'),
 ('312272', 'C0000010545'),
 ('312272', 'C0000005901'),
 ('312272', 'C0000010546'),
 ('312272', 'C0000005902'),
 ('312272', 'C0000010547'),
 ('312272', 'P11212036'),
 ('312272', 'P11220274'),
 ('312272', 'P11270103'),
 ('312272', 'P11241782'),
 ('312272', 'P11270073'),
 ('312272', 'P11270110'),
 ('312272', 'P11270195'),
 ('312272', 'P11270120'),
 ('312273', 'C0000005895'),
 ('312273', 'C0000010548'),
 ('312273', 'C0000005896'),
 ('312273', 'C0000010549'),
 ('312273', 'C0000005897'),
 ('312273', 'C0000010550'),
 ('312273', 'C0000005898'),
 ('312273', 'C0000010551'),
 ('312273', 'P11212037'),
 ('312273', 'P11220274'),
 ('312273', 'P11270104'),
 ('312273', 'P11241783'),
 ('312273', 'P11270073'),
 ('312273', 'P11270110'),
 ('312273', 'P11270195'),
 ('312273', 'P11270120'),
 ('312950', 'C0000010485'),
 ('312950', 'C0000010484'),
 ('312950', 'C0000010483'),
 ('312950', 'C0000010482'),
 ('312950', 'P11212262'),
 ('312950', 'P11220274'),
 ('312950', 'P11260165'),
 ('312950', 'P11241803'),
 ('312950', 'P11270120'),
 ('312950', 'P11270110'),
 ('312950', 'P11270195'),
 ('312950', 'P11250825'),
 ('312950', 'P11270073'),
 ('731059', 'C0000009481'),
 ('731059', 'C0000010388'),
 ('731059', 'C0000009480'),
 ('731059', 'C0000010387'),
 ('731059', 'C0000009478'),
 ('731059', 'C0000010385'),
 ('731059', 'P11241929'),
 ('731059', 'P11212412'),
 ('731059', 'P11280012'),
 ('731059', 'P11220259'),
 ('731059', 'P11270073'),
 ('731059', 'P11270120'),
 ('731059', 'P11270110'),
 ('731059', 'P11270195'),
 ('731059', 'C0000009479'),
 ('731059', 'C0000010386'),
 ('731059', 'P11250912'),
 ('1050301', 'C0000004023'),
 ('1050301', 'C0000004024'),
 ('1050301', 'C0000004025'),
 ('1050301', 'C0000004026'),
 ('1050301', 'P11211060'),
 ('1050301', 'P11230018'),
 ('1050301', 'P11270079'),
 ('1050301', 'P11250077'),
 ('1050301', 'P11241127'),
 ('1050301', 'P11220262'),
 ('1050301', 'P11270073'),
 ('1050302', 'C0000009120'),
 ('1050302', 'C0000009121'),
 ('1050302', 'C0000009122'),
 ('1050302', 'C0000009123'),
 ('1050302', 'P11212331'),
 ('1050302', 'P11230088'),
 ('1050302', 'P11270079'),
 ('1050302', 'P11250078'),
 ('1050302', 'P11241951'),
 ('1050302', 'P11220274'),
 ('1050302', 'P11270073'),
 ('1050339', 'C0000003790'),
 ('1050339', 'C0000003791'),
 ('1050339', 'C0000003792'),
 ('1050339', 'C0000003793'),
 ('1050339', 'P11211588'),
 ('1050339', 'P11220274'),
 ('1050339', 'P11230088'),
 ('1050339', 'P11270079'),
 ('1050339', 'P11250253'),
 ('1050339', 'P11241090'),
 ('1050339', 'P11270073'),
 ('1050339', 'P11270132'),
 ('1050341', 'C0000003790'),
 ('1050341', 'C0000003791'),
 ('1050341', 'C0000003792'),
 ('1050341', 'C0000003793'),
 ('1050341', 'P11211472'),
 ('1050341', 'P11220259'),
 ('1050341', 'P11250564'),
 ('1050341', 'P11230018'),
 ('1050341', 'P11270079'),
 ('1050341', 'P11250055'),
 ('1050341', 'P11270073'),
 ('1050341', 'P11241107'),
 ('1050345', '32135'),
 ('1050345', '32136'),
 ('1050345', '32137'),
 ('1050345', '32138'),
 ('1050345', 'P11212145'),
 ('1050345', 'P11220258'),
 ('1050345', 'P11241869'),
 ('1050345', 'P11270073'),
 ('1050345', 'P11270106'),
 ('1050346', '31388'),
 ('1050346', '31390'),
 ('1050346', '31392'),
 ('1050346', '31394'),
 ('1050346', 'P11260124'),
 ('1050346', 'P11241130'),
 ('1050346', 'P11270056'),
 ('1050347', 'C0000009120'),
 ('1050347', 'C0000009121'),
 ('1050347', 'C0000009122'),
 ('1050347', 'C0000009123'),
 ('1050347', 'P11212252'),
 ('1050347', 'P11220259'),
 ('1050347', 'P11250821'),
 ('1050347', 'P11241867'),
 ('1050347', 'P11230088'),
 ('1050347', 'P11270079'),
 ('1050347', 'P11270073'),
 ('1050348', 'C0000003790'),
 ('1050348', 'C0000003791'),
 ('1050348', 'C0000003792'),
 ('1050348', 'C0000003793'),
 ('1050348', 'P11211804'),
 ('1050348', 'P11220264'),
 ('1050348', 'P11241521'),
 ('1050348', 'P11270073'),
 ('1050348', 'P11270106'),
 ('1050350', 'C0000009120'),
 ('1050350', 'C0000009121'),
 ('1050350', 'C0000009122'),
 ('1050350', 'C0000009123'),
 ('1050350', 'P11212259'),
 ('1050350', 'P11220274'),
 ('1050350', 'P11230088'),
 ('1050350', 'P11270079'),
 ('1050350', 'P11250089'),
 ('1050350', 'P11241965'),
 ('1050350', 'P11270073'),
 ('1050351', 'C0000009112'),
 ('1050351', 'C0000009113'),
 ('1050351', 'C0000009114'),
 ('1050351', 'C0000009115'),
 ('1050351', 'P11212260'),
 ('1050351', 'P11220274'),
 ('1050351', 'P11230088'),
 ('1050351', 'P11270079'),
 ('1050351', 'P11250090'),
 ('1050351', 'P11241964'),
 ('1050351', 'P11270073'),
 ('1050352', '32135'),
 ('1050352', '32136'),
 ('1050352', '32137'),
 ('1050352', '32138'),
 ('1050352', 'P11212251'),
 ('1050352', 'P11220258'),
 ('1050352', 'P11241874'),
 ('1050352', 'P11270073'),
 ('1050352', 'P11270106'),
 ('1050413', 'C0000003732'),
 ('1050413', 'C0000003733'),
 ('1050413', 'C0000003734'),
 ('1050413', 'C0000003735'),
 ('1050413', 'P11230018'),
 ('1050413', 'P11270079'),
 ('1050413', 'P11250172'),
 ('1050413', 'P11241132'),
 ('1050413', 'P11270073'),
 ('1050413', 'P11211063'),
 ('1050413', 'P11220262'),
 ('1050420', 'C0000004678'),
 ('1050420', 'C0000003670'),
 ('1050420', 'C0000003671'),
 ('1050420', 'C0000003672'),
 ('1050420', 'P11230018'),
 ('1050420', 'P11270079'),
 ('1050420', 'P11241133'),
 ('1050420', 'P11270073'),
 ('1050420', 'P11211062'),
 ('1050420', 'P11220262'),
 ('1050420', 'P11250152'),
 ('1050421', 'C0000003732'),
 ('1050421', 'C0000003733'),
 ('1050421', 'C0000003734'),
 ('1050421', 'C0000003735'),
 ('1050421', 'P11270067'),
 ('1050421', 'P11230069'),
 ('1050421', 'P11241134'),
 ('1050421', 'P11270056'),
 ('1050434', 'C0000003732'),
 ('1050434', 'C0000003733'),
 ('1050434', 'C0000003734'),
 ('1050434', 'C0000003735'),
 ('1050434', 'P11220156'),
 ('1050434', 'P11210910'),
 ('1050434', 'P11260097'),
 ('1050434', 'P11240960'),
 ('1050434', 'P11270012'),
 ('1050434', 'P11270110'),
 ('1050434', 'P11270073'),
 ('1050435', 'C0000006612'),
 ('1050435', 'C0000006611'),
 ('1050435', 'C0000006610'),
 ('1050435', 'C0000006609'),
 ('1050435', 'P11220264'),
 ('1050435', 'P11241840'),
 ('1050435', 'P11270073'),
 ('1050435', 'P11270120'),
 ('1050435', 'P11270110'),
 ('1050435', 'P11270106'),
 ('1050435', 'P11212104'),
 ('1050436', 'C0000006612'),
 ('1050436', 'C0000006611'),
 ('1050436', 'C0000006610'),
 ('1050436', 'C0000006609'),
 ('1050436', 'P11212105'),
 ('1050436', 'P11220258'),
 ('1050436', 'P11241842'),
 ('1050436', 'P11270073'),
 ('1050436', 'P11270110'),
 ('1050436', 'P11270120'),
 ('1050436', 'P11270106'),
 ('1050437', 'C0000006612'),
 ('1050437', 'C0000006611'),
 ('1050437', 'C0000006610'),
 ('1050437', 'C0000006609'),
 ('1050437', 'P11210969'),
 ('1050437', 'P11220156'),
 ('1050437', 'P11260137'),
 ('1050437', 'P11241353'),
 ('1050437', 'P11270012'),
 ('1050437', 'P11270110'),
 ('1050437', 'P11270073'),
 ('1050438', 'C0000006612'),
 ('1050438', 'C0000006611'),
 ('1050438', 'C0000006610'),
 ('1050438', 'C0000006609'),
 ('1050438', 'P11270067'),
 ('1050438', 'P11230081'),
 ('1050438', 'P11240621'),
 ('1050438', 'P11270056'),
 ('1050438', 'P11270012'),
 ('1050438', 'P11270110'),
 ('1050446', '32380'),
 ('1050446', '32381'),
 ('1050446', '32382'),
 ('1050446', '32383'),
 ('1050446', 'P11212269'),
 ('1050446', 'P11220267'),
 ('1050446', 'P11250828'),
 ('1050446', 'P11230091'),
 ('1050446', 'P11270079'),
 ('1050446', 'P11241832'),
 ('1050446', 'P11270073'),
 ('1050447', 'C0000003790'),
 ('1050447', 'C0000003791'),
 ('1050447', 'C0000003792'),
 ('1050447', 'C0000003793'),
 ('1050447', 'P11210955'),
 ('1050447', 'P11220213'),
 ('1050447', 'P11241074'),
 ('1050447', 'P11270106'),
 ('1050447', 'P11270073'),
 ('1050447', 'P11220257'),
 ('1050448', 'C0000003790'),
 ('1050448', 'C0000003791'),
 ('1050448', 'C0000003792'),
 ('1050448', 'C0000003793'),
 ('1050448', 'P11211598'),
 ('1050448', 'P11220274'),
 ('1050448', 'P11230088'),
 ('1050448', 'P11250423'),
 ('1050448', 'P11270079'),
 ('1050448', 'P11241136'),
 ('1050448', 'P11270073'),
 ('1050448', 'P11270110'),
 ('1050448', 'P11270120'),
 ('1050448', 'P11270132'),
 ('1050449', '32135'),
 ('1050449', '32136'),
 ('1050449', '32137'),
 ('1050449', '32138'),
 ('1050449', 'P11241872'),
 ('1050449', 'P11270192'),
 ('1050449', 'P11270097'),
 ('1050449', 'P11270073'),
 ('1050452', 'C0000003790'),
 ('1050452', 'C0000003791'),
 ('1050452', 'C0000003792'),
 ('1050452', 'C0000003793'),
 ('1050452', 'P11211135'),
 ('1050452', 'P11220213'),
 ('1050452', 'P11241076'),
 ('1050452', 'P11270073'),
 ('1050452', 'P11270106'),
 ('1050452', 'P11220264'),
 ('1050454', 'C0000004788'),
 ('1050454', 'P11241009'),
 ('1050454', 'P11270056'),
 ('1050454', 'P11270067'),
 ('1050455', 'C0000004789'),
 ('1050455', 'P11241009'),
 ('1050455', 'P11270056'),
 ('1050455', 'P11270067'),
 ('1050456', 'C0000004790'),
 ('1050456', 'P11241009'),
 ('1050456', 'P11270056'),
 ('1050456', 'P11270067'),
 ('1050457', 'C0000004791'),
 ('1050457', 'P11241009'),
 ('1050457', 'P11270056'),
 ('1050457', 'P11270067'),
 ('1050458', 'C0000009107'),
 ('1050458', 'P11270067'),
 ('1050458', 'P11241030'),
 ('1050458', 'P11270056'),
 ('1050458', 'P11270120'),
 ('1050458', 'P11270110'),
 ('1050458', 'P11270195'),
 ('1050459', 'C0000009105'),
 ('1050459', 'P11270067'),
 ('1050459', 'P11241030'),
 ('1050459', 'P11270056'),
 ('1050459', 'P11270120'),
 ('1050459', 'P11270110'),
 ('1050459', 'P11270195'),
 ('1050460', 'C0000009106'),
 ('1050460', 'P11270067'),
 ('1050460', 'P11241030'),
 ('1050460', 'P11270056'),
 ('1050460', 'P11270120'),
 ('1050460', 'P11270110'),
 ('1050460', 'P11270195'),
 ('1050461', 'C0000009104'),
 ('1050461', 'P11270067'),
 ('1050461', 'P11241030'),
 ('1050461', 'P11270056'),
 ('1050461', 'P11270120'),
 ('1050461', 'P11270110'),
 ('1050461', 'P11270195'),
 ('1050463', 'C0000009109'),
 ('1050463', 'P11270067'),
 ('1050463', 'P11241031'),
 ('1050463', 'P11270056'),
 ('1050463', 'P11270120'),
 ('1050463', 'P11270110'),
 ('1050464', 'C0000009108'),
 ('1050464', 'P11270067'),
 ('1050464', 'P11241031'),
 ('1050464', 'P11270056'),
 ('1050464', 'P11270120'),
 ('1050464', 'P11270110'),
 ('1050464', 'P11270195'),
 ('1050465', 'C0000009110'),
 ('1050465', 'P11270067'),
 ('1050465', 'P11241031'),
 ('1050465', 'P11270056'),
 ('1050465', 'P11270120'),
 ('1050465', 'P11270110'),
 ('1050465', 'P11270195'),
 ('1050466', 'C0000009111'),
 ('1050466', 'P11270067'),
 ('1050466', 'P11241031'),
 ('1050466', 'P11270056'),
 ('1050466', 'P11270120'),
 ('1050466', 'P11270110'),
 ('1050466', 'P11270195'),
 ('1050467', 'C0000010478'),
 ('1050467', 'C0000010479'),
 ('1050467', 'C0000010480'),
 ('1050467', 'C0000010481'),
 ('1050467', 'P11212257'),
 ('1050467', 'P11220274'),
 ('1050467', 'P11230088'),
 ('1050467', 'P11270079'),
 ('1050467', 'P11250900'),
 ('1050467', 'P11241966'),
 ('1050467', 'P11270073'),
 ('1050468', 'C0000010485'),
 ('1050468', 'C0000010484'),
 ('1050468', 'C0000010483'),
 ('1050468', 'C0000010482'),
 ('1050468', 'P11230088'),
 ('1050468', 'P11270079'),
 ('1050468', 'P11250152'),
 ('1050468', 'P11241818'),
 ('1050468', 'P11270073'),
 ('1050468', 'P11212510'),
 ('1050468', 'P11220274'),
 ('1050507', 'P11242064'),
 ('1050507', 'P11212364'),
 ('1050507', 'P11220274'),
 ('1050507', 'P11250276'),
 ('1050507', 'P11270073'),
 ('1050507', '32236'),
 ('1050507', '32346'),
 ('1050507', '32239'),
 ('1050507', '32347'),
 ('1050507', '32237'),
 ('1050507', '32348'),
 ('1050507', '32238'),
 ('1050507', '32349'),
 ('1050507', 'P11230088'),
 ('1050507', 'P11270079'),
 ('1050528', 'C0000009477'),
 ('1050528', 'C0000010392'),
 ('1050528', 'C0000009476'),
 ('1050528', 'C0000010391'),
 ('1050528', 'C0000009474'),
 ('1050528', 'C0000010389'),
 ('1050528', 'C0000009475'),
 ('1050528', 'C0000010390'),
 ('1050528', 'P11212330'),
 ('1050528', 'P11220271'),
 ('1050528', 'P11250867'),
 ('1050528', 'P11230080'),
 ('1050528', 'P11270005'),
 ('1050528', 'P11241363'),
 ('1050528', 'P11270073'),
 ('1050528', 'P11250388'),
 ('1050529', 'C0000005148'),
 ('1050529', 'C0000005149'),
 ('1050529', 'C0000005150'),
 ('1050529', 'C0000005151'),
 ('1050529', 'P11270079'),
 ('1050529', 'P11230073'),
 ('1050529', 'P11240909'),
 ('1050529', 'P11270073'),
 ('1050529', 'P11211780'),
 ('1050529', 'P11220280'),
 ('1050529', 'P11250384'),
 ('1050530', 'C0000005155'),
 ('1050530', 'C0000005156'),
 ('1050530', 'C0000005157'),
 ('1050530', 'C0000005158'),
 ('1050530', 'P11270079'),
 ('1050530', 'P11230073'),
 ('1050530', 'P11240908'),
 ('1050530', 'P11270073'),
 ('1050530', 'P11211781'),
 ('1050530', 'P11220280'),
 ('1050530', 'P11250383'),
 ('1050533', 'C0000009481'),
 ('1050533', 'C0000010388'),
 ('1050533', 'C0000009480'),

In [87]:
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.children = []

def build_tree(list_pair, parent, tree):
    children = [child for parent_name, child in list_pair if parent_name == parent.value]

    for child_value in children:
        child_node = TreeNode(child_value)
        parent.children.append(child_node)
        build_tree(list_pair, child_node, tree)

def get_tree_hierarchy(node, path=[]):
    path.append(node.value)
    hierarchy = []

    if not node.children:
        hierarchy.append(path.copy())

    for child in node.children:
        hierarchy.extend(get_tree_hierarchy(child, path.copy()))

    path.pop()
    return hierarchy


unique_parents = set(parent for parent, _ in list_pair)
unique_children = set(child for _, child in list_pair)

root_names = list(unique_parents - unique_children)

root_nodes = [TreeNode(name) for name in root_names]

for root in root_nodes:
    build_tree(list_pair, root, root)

hierarchies = []
for root in root_nodes:
    hierarchies.extend(get_tree_hierarchy(root))

# Convert the hierarchies list into a DataFrame
BOMtree = pd.DataFrame(hierarchies)

In [88]:
BOMtree

                 0            1            2       3     4     5
0          1051620  C0000002485  C0000002941  M43203  None  None
1          1051620  C0000002485  C0000002941  M22711  None  None
2          1051620  C0000002485       M37819    None  None  None
3          1051620  C0000002485       M31079    None  None  None
4          1051620  C0000002485       M31436    None  None  None
...            ...          ...          ...     ...   ...   ...
28726  C0000002089       M30710         None    None  None  None
28727  C0000002089  C0000002086       M21165    None  None  None
28728  C0000002089  C0000002086       M36803    None  None  None
28729  C0000002089  C0000002086  C0000002083  M21165  None  None
28730  C0000002089  C0000002086  C0000002083  M22626  None  None

[28731 rows x 6 columns]

## 3.4 MERGE BOMTREE WITH MARC

In [89]:
sql_marc = 'SELECT * FROM "SBX_SC_HUB"."MP3_DATA"."MP3_MARC"'
cur.execute(sql_marc)
df_marc = cur.fetch_pandas_all()
df_marc

,MATERIAL,PLANT,MAINTENANCE_STATUS,BATCH_MANAGEMENT,PLANT_SP_MATL_STATUS,VALID_FROM,MRP_TYPE,MRP_CONTROLLER,PLANNED_DELIV_TIME,GR_PROCESSING_TIME,...,COVERAGE_PROFILE,SELECTION_METHOD,INDIVIDUAL_COLL,PROD_SCHED_PROFILE,VERSION_INDICATOR,UNDERDELY_TOLERANCE,OVERDELY_TOLERANCE,UNLTD_OVERDELIVERY,ABC_INDICATOR,INSPECTION_PLAN_IND
0,C0000000987,VN11,LGBDESA,,C5,None,ND,TBD,0,0,...,,2,2,VN11IM,X,0.0,0.0,X,,
1,C0000000990,VN11,LBGDESV,,C5,None,ND,TBD,0,0,...,,2,2,,X,0.0,0.0,,,
2,C0000000994,VN11,LBGDESV,,C5,None,ND,TBD,0,0,...,,2,2,,X,0.0,0.0,,,
3,P11270056,VN11,DBGLESQV,X,C3,None,PD,TBI,20,1,...,,2,2,,,0.0,0.0,,A,
4,Z105BE00281,VN11,EDL,,12,None,ND,SP1,30,0,...,,,,,,0.0,0.0,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12104,P11212357,VN11,LSBGQED,X,C8,None,PD,TB4,7,1,...,,2,2,,,0.0,0.0,,B,
12105,P11212446,VN11,LSQBGED,X,C8,None,PD,TB4,8,1,...,,2,2,,,0.0,0.0,,B,
12106,P11212059,VN11,LQSBGED,X,C5,None,ND,TBD,7,1,...,,2,2,,,0.0,0.0,,C,
12107,P11212060,VN11,LQSBGED,X,C5,None,ND,TBD,7,1,...,,2,2,,,0.0,0.0,,C,
12108,P11212061,VN11,LQSBGED,X,C5,None,ND,TBD,10,1,...,,2,2,,,0.0,0.0,,C,

In [90]:
BOMtree = BOMtree.merge(df_marc[['MATERIAL', 'PLANT_SP_MATL_STATUS','PLANT']], how='left', left_on=0, right_on='MATERIAL')
BOMtree = BOMtree[~(BOMtree["PLANT_SP_MATL_STATUS"] == 'C5')]
BOMtree = BOMtree.drop(columns=['MATERIAL', 'PLANT_SP_MATL_STATUS','PLANT'])
BOMtree

              0            1            2       3     4     5
65     VN01289A  C0000009305       M22411    None  None  None
66     VN01289A  C0000009305       M44034    None  None  None
67     VN01289A  C0000009305       M44761    None  None  None
68     VN01289A  C0000009305       M44030    None  None  None
69     VN01289A  C0000009305  C0000009257  M27839  None  None
...         ...          ...          ...     ...   ...   ...
28668  FVN00156    P11241721         None    None  None  None
28669  FVN00156    P11270073         None    None  None  None
28670  FVN00156    P11270120         None    None  None  None
28671  FVN00156    P11270110         None    None  None  None
28672  FVN00156    P11270195         None    None  None  None

[13510 rows x 6 columns]

## 3.5 EXTRACT CONSUMPTION RATIO

In [91]:
df_ratio = df.iloc[:, [0,8,2,4]].copy()
df_ratio

       Material Material Quantity    Component Component Quantity
0         31371         1,000.000  C0000000934          1,000.000
1         31371         1,000.000    P11230075          1,000.000
2         31372         1,000.000  C0000001016          1,000.000
3         31372         1,000.000    P11230075          1,000.000
4         31373         1,000.000  C0000001017          1,000.000
...         ...               ...          ...                ...
29657  VN01327A         1,000.000    P11211726        144,000.000
29658  VN01327A         1,000.000    P11220265            548.370
29659  VN01327A         1,000.000    P11241570          1,000.000
29660  VN01327A         1,000.000    P11270106              1.200
29661  VN01327A         1,000.000    P11270073              1.160

[11606 rows x 4 columns]

In [92]:
df_ratio['Component Quantity'] = df_ratio['Component Quantity'].str.replace(',', '').astype(float)
df_ratio['Material Quantity'] = df_ratio['Material Quantity'].str.replace(',', '').astype(float)
df_ratio['Ratio'] = df_ratio['Component Quantity'] / df_ratio['Material Quantity']
df_ratio = df_ratio[['Material','Component','Ratio']]

### LIST SUM

In [93]:
df_list_sum = pd.read_csv(folder_path + "List material cum sum.csv", delimiter=',')
df_list_sum = df_list_sum.drop_duplicates()
df_list_sum['Sum']='Yes'
df_list_sum

       Material Component  Sum
0   C0000002130    M30701  Yes
1   C0000005544    M21165  Yes
3   C0000005545    M21165  Yes
5   C0000005546    M21165  Yes
7   C0000009992    M38273  Yes
8   C0000009992    M19934  Yes
11  C0000009993    M38273  Yes
12  C0000009993    M19934  Yes
15  C0000009994    M38273  Yes
16  C0000009994    M19934  Yes
19  C0000009995    M38273  Yes
20  C0000009995    M19934  Yes
23  C0000006576    M21165  Yes
24  C0000006577    M21165  Yes
25  C0000006578    M21165  Yes
26  C0000006579    M21165  Yes

In [94]:
df_ratio = df_ratio.merge(df_list_sum, how='left', on=['Material','Component'])
df_ratio['Ratio'] = np.where(df_ratio['Sum'] == 'Yes', df_ratio.groupby(['Material', 'Component','Sum'])['Ratio'].transform('sum'), df_ratio['Ratio'])
df_ratio = df_ratio.drop('Sum', axis=1)
df_ratio

       Material    Component      Ratio
0         31371  C0000000934    1.00000
1         31371    P11230075    1.00000
2         31372  C0000001016    1.00000
3         31372    P11230075    1.00000
4         31373  C0000001017    1.00000
...         ...          ...        ...
11601  VN01327A    P11211726  144.00000
11602  VN01327A    P11220265    0.54837
11603  VN01327A    P11241570    1.00000
11604  VN01327A    P11270106    0.00120
11605  VN01327A    P11270073    0.00116

[11606 rows x 3 columns]

In [95]:
# Find the index of the rows with the highest ratio within each group
idx = df_ratio.groupby(['Material', 'Component'])['Ratio'].idxmax()

# Select rows using the index
df_ratio_max = df_ratio.loc[idx]

# Reset the index if needed
df_ratio_max = df_ratio_max.reset_index(drop=True)

df_ratio_max

       Material    Component      Ratio
0       1050301  C0000004023   18.00000
1       1050301  C0000004024   18.00000
2       1050301  C0000004025   18.00000
3       1050301  C0000004026   18.00000
4       1050301    P11211060   72.00000
...         ...          ...        ...
11476  VN01327A    P11211726  144.00000
11477  VN01327A    P11220265    0.54837
11478  VN01327A    P11241570    1.00000
11479  VN01327A    P11270073    0.00116
11480  VN01327A    P11270106    0.00120

[11481 rows x 3 columns]

In [96]:
BOMtree.columns = ['lv1', 'lv2', 'lv3', 'lv4', 'lv5', 'lv6']
BOMtree = BOMtree.fillna('null')
BOMtree

            lv1          lv2          lv3     lv4   lv5   lv6
65     VN01289A  C0000009305       M22411    null  null  null
66     VN01289A  C0000009305       M44034    null  null  null
67     VN01289A  C0000009305       M44761    null  null  null
68     VN01289A  C0000009305       M44030    null  null  null
69     VN01289A  C0000009305  C0000009257  M27839  null  null
...         ...          ...          ...     ...   ...   ...
28668  FVN00156    P11241721         null    null  null  null
28669  FVN00156    P11270073         null    null  null  null
28670  FVN00156    P11270120         null    null  null  null
28671  FVN00156    P11270110         null    null  null  null
28672  FVN00156    P11270195         null    null  null  null

[13510 rows x 6 columns]

## 3.6 CREATE BOMTREE WITH RATIO

In [97]:
BOMtree_ratio = BOMtree.copy()

In [98]:
def left_merge_dataframes_ratio(left_col1, left_col2):
    global BOMtree_ratio
    
    result_df = pd.merge(BOMtree_ratio, df_ratio_max, how='left', left_on=[left_col1, left_col2], right_on=['Material', 'Component'])
    
    # Drop 'Material' and 'Component' columns
    result_df = result_df.drop(columns=['Material', 'Component'])
    
    # Rename columns with suffixes based on the input column names
    result_df = result_df.rename(columns={
        'Ratio': 'Ratio_' + left_col2
    })
    
    BOMtree_ratio = result_df  # Update the global variable
    return BOMtree_ratio

# Call the function for each pair of columns
left_merge_dataframes_ratio('lv1', 'lv2')
left_merge_dataframes_ratio('lv2', 'lv3')
left_merge_dataframes_ratio('lv3', 'lv4')
left_merge_dataframes_ratio('lv4', 'lv5')
left_merge_dataframes_ratio('lv5', 'lv6')

,lv1,lv2,lv3,lv4,lv5,lv6,Ratio_lv2,Ratio_lv3,Ratio_lv4,Ratio_lv5,Ratio_lv6
0,VN01289A,C0000009305,M22411,null,null,null,18.000000,0.000076,NaN,NaN,NaN
1,VN01289A,C0000009305,M44034,null,null,null,18.000000,0.000510,NaN,NaN,NaN
2,VN01289A,C0000009305,M44761,null,null,null,18.000000,0.000151,NaN,NaN,NaN
3,VN01289A,C0000009305,M44030,null,null,null,18.000000,0.000250,NaN,NaN,NaN
4,VN01289A,C0000009305,C0000009257,M27839,null,null,18.000000,1.000000,0.002646,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,P11241721,null,null,null,null,1.000000,NaN,NaN,NaN,NaN
13506,FVN00156,P11270073,null,null,null,null,0.000900,NaN,NaN,NaN,NaN
13507,FVN00156,P11270120,null,null,null,null,0.012500,NaN,NaN,NaN,NaN
13508,FVN00156,P11270110,null,null,null,null,0.006188,NaN,NaN,NaN,NaN
13509,FVN00156,P11270195,null,null,null,null,0.003160,NaN,NaN,NaN,NaN

## 3.7 RELAYOUT

### DEAL WITH 3*

In [99]:
# Create an empty dictionary to store the result
BOMtree_temp = {}

# Iterate through DataFrame rows
for index, row in BOMtree_ratio.iterrows():
    BOMtree_temp[index] = []

    # Iterate through columns for each row
    for col in range(len(row)):
        value = row[col]

        # Check if the value is not None and not NaN (if NaN values exist)
        if pd.notna(value) and value is not None:
            BOMtree_temp[index].append(value)

# Create an empty dictionary for the transformed data
BOMtree_transformed = {}

# Iterate through the BOMtree data and apply the transformation rule
for key, values in BOMtree_temp.items():
    if values[1] is not None and values[1].startswith('3'):
        BOMtree_transformed[key] = values  # Keep the same as origin
    else:
        # Rearrange the column positions as specified
        transformed_values = [values[0]] + [None] * 1  # Initialize with 5 elements
        transformed_values.extend(values[1:])  # Add remaining elements from the original data
        BOMtree_transformed[key] = transformed_values

# Print the transformed data
for key, values in BOMtree_transformed.items():
    print(key, values)

0 ['VN01289A', None, 'C0000009305', 'M22411', 'null', 'null', 'null', 18.0, 7.6e-05]
1 ['VN01289A', None, 'C0000009305', 'M44034', 'null', 'null', 'null', 18.0, 0.00051]
2 ['VN01289A', None, 'C0000009305', 'M44761', 'null', 'null', 'null', 18.0, 0.00015099999999999998]
3 ['VN01289A', None, 'C0000009305', 'M44030', 'null', 'null', 'null', 18.0, 0.00025]
4 ['VN01289A', None, 'C0000009305', 'C0000009257', 'M27839', 'null', 'null', 18.0, 1.0, 0.002646]
5 ['VN01289A', None, 'C0000009305', 'C0000009257', 'M37998', 'null', 'null', 18.0, 1.0, 5.4e-05]
6 ['VN01289A', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M29142', 'null', 18.0, 1.0, 1.0, 0.000279]
7 ['VN01289A', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M38272', 'null', 18.0, 1.0, 1.0, 0.00451]
8 ['VN01289A', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M40443', 'null', 18.0, 1.0, 1.0, 0.00451]
9 ['VN01289A', None, 'C0000009306', 'M22411', 'null', 'null', 'null', 18.0, 7.6e-05]
10 ['VN01289A', None, 'C0000009306', 'M44034', 'null', 'null', 'null', 18.0, 0.00051]
11 ['VN01289A', None, 'C0000009306', 'M44761', 'null', 'null', 'null', 18.0, 0.00015099999999999998]
12 ['VN01289A', None, 'C0000009306', 'M44030', 'null', 'null', 'null', 18.0, 0.00025]
13 ['VN01289A', None, 'C0000009306', 'C0000009256', 'M27839', 'null', 'null', 18.0, 1.0, 0.002646]
14 ['VN01289A', None, 'C0000009306', 'C0000009256', 'M37998', 'null', 'null', 18.0, 1.0, 5.4e-05]
15 ['VN01289A', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M38252', 'null', 18.0, 1.0, 1.0, 0.000372]
16 ['VN01289A', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M38272', 'null', 18.0, 1.0, 1.0, 0.004464]
17 ['VN01289A', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M40443', 'null', 18.0, 1.0, 1.0, 0.004464]
18 ['VN01289A', None, 'C0000009307', 'M22411', 'null', 'null', 'null', 18.0, 7.6e-05]
19 ['VN01289A', None, 'C0000009307', 'M44034', 'null', 'null', 'null', 18.0, 0.00051]
20 ['VN01289A', None, 'C0000009307', 'M44761', 'null', 'null', 'null', 18.0, 0.00015099999999999998]
21 ['VN01289A', None, 'C0000009307', 'M44030', 'null', 'null', 'null', 18.0, 0.00025]
22 ['VN01289A', None, 'C0000009307', 'C0000009255', 'M27839', 'null', 'null', 18.0, 1.0, 0.002646]
23 ['VN01289A', None, 'C0000009307', 'C0000009255', 'M37998', 'null', 'null', 18.0, 1.0, 5.4e-05]
24 ['VN01289A', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M44307', 'null', 18.0, 1.0, 1.0, 0.000372]
25 ['VN01289A', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M38272', 'null', 18.0, 1.0, 1.0, 0.004464]
26 ['VN01289A', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M40443', 'null', 18.0, 1.0, 1.0, 0.004464]
27 ['VN01289A', None, 'C0000009308', 'M22411', 'null', 'null', 'null', 18.0, 7.6e-05]
28 ['VN01289A', None, 'C0000009308', 'M44034', 'null', 'null', 'null', 18.0, 0.00051]
29 ['VN01289A', None, 'C0000009308', 'M44761', 'null', 'null', 'null', 18.0, 0.00015099999999999998]
30 ['VN01289A', None, 'C0000009308', 'M44030', 'null', 'null', 'null', 18.0, 0.00025]
31 ['VN01289A', None, 'C0000009308', 'C0000009258', 'M27839', 'null', 'null', 18.0, 1.0, 0.002646]
32 ['VN01289A', None, 'C0000009308', 'C0000009258', 'M37998', 'null', 'null', 18.0, 1.0, 5.4e-05]
33 ['VN01289A', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M25064', 'null', 18.0, 1.0, 1.0, 0.000372]
34 ['VN01289A', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M38272', 'null', 18.0, 1.0, 1.0, 0.004464]
35 ['VN01289A', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M40443', 'null', 18.0, 1.0, 1.0, 0.004464]
36 ['VN01289A', None, 'P11212272', 'null', 'null', 'null', 'null', 72.0]
37 ['VN01289A', None, 'P11220274', 'null', 'null', 'null', 'null', 0.309485]
38 ['VN01289A', None, 'P11230088', 'null', 'null', 'null', 'null', 6.0]
39 ['VN01289A', None, 'P11270079', 'null', 'null', 'null', 'null', 0.0189]
40 ['VN01289A', None, 'P11250603', 'null', 'null', 'null', 'null', 6.0]
41 ['VN01289A', None, 'P11241974', 'null', 'null', 'null', 'null', 1.0]
42 ['VN01289A', None, 'P11270073', 'null', 'null', 'null', 'null', 0.0012]
43 ['61030123', None, 'C0000009305', 'M22411', 'null', 'null', 'null', 6.0, 7.6e-05]
44 ['61030123', None, 'C0000009305', 'M44034', 'null', 'null', 'null', 6.0, 0.00051]
45 ['61030123', None, 'C0000009305', 'M44761', 'null', 'null', 'null', 6.0, 0.00015099999999999998]
46 ['61030123', None, 'C0000009305', 'M44030', 'null', 'null', 'null', 6.0, 0.00025]
47 ['61030123', None, 'C0000009305', 'C0000009257', 'M27839', 'null', 'null', 6.0, 1.0, 0.002646]
48 ['61030123', None, 'C0000009305', 'C0000009257', 'M37998', 'null', 'null', 6.0, 1.0, 5.4e-05]
49 ['61030123', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M29142', 'null', 6.0, 1.0, 1.0, 0.000279]
50 ['61030123', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M38272', 'null', 6.0, 1.0, 1.0, 0.00451]
51 ['61030123', None, 'C0000009305', 'C0000009257', 'C0000009240', 'M40443', 'null', 6.0, 1.0, 1.0, 0.00451]
52 ['61030123', None, 'C0000009306', 'M22411', 'null', 'null', 'null', 6.0, 7.6e-05]
53 ['61030123', None, 'C0000009306', 'M44034', 'null', 'null', 'null', 6.0, 0.00051]
54 ['61030123', None, 'C0000009306', 'M44761', 'null', 'null', 'null', 6.0, 0.00015099999999999998]
55 ['61030123', None, 'C0000009306', 'M44030', 'null', 'null', 'null', 6.0, 0.00025]
56 ['61030123', None, 'C0000009306', 'C0000009256', 'M27839', 'null', 'null', 6.0, 1.0, 0.002646]
57 ['61030123', None, 'C0000009306', 'C0000009256', 'M37998', 'null', 'null', 6.0, 1.0, 5.4e-05]
58 ['61030123', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M38252', 'null', 6.0, 1.0, 1.0, 0.000372]
59 ['61030123', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M38272', 'null', 6.0, 1.0, 1.0, 0.004464]
60 ['61030123', None, 'C0000009306', 'C0000009256', 'C0000009241', 'M40443', 'null', 6.0, 1.0, 1.0, 0.004464]
61 ['61030123', None, 'C0000009307', 'M22411', 'null', 'null', 'null', 6.0, 7.6e-05]
62 ['61030123', None, 'C0000009307', 'M44034', 'null', 'null', 'null', 6.0, 0.00051]
63 ['61030123', None, 'C0000009307', 'M44761', 'null', 'null', 'null', 6.0, 0.00015099999999999998]
64 ['61030123', None, 'C0000009307', 'M44030', 'null', 'null', 'null', 6.0, 0.00025]
65 ['61030123', None, 'C0000009307', 'C0000009255', 'M27839', 'null', 'null', 6.0, 1.0, 0.002646]
66 ['61030123', None, 'C0000009307', 'C0000009255', 'M37998', 'null', 'null', 6.0, 1.0, 5.4e-05]
67 ['61030123', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M44307', 'null', 6.0, 1.0, 1.0, 0.000372]
68 ['61030123', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M38272', 'null', 6.0, 1.0, 1.0, 0.004464]
69 ['61030123', None, 'C0000009307', 'C0000009255', 'C0000009242', 'M40443', 'null', 6.0, 1.0, 1.0, 0.004464]
70 ['61030123', None, 'C0000009308', 'M22411', 'null', 'null', 'null', 6.0, 7.6e-05]
71 ['61030123', None, 'C0000009308', 'M44034', 'null', 'null', 'null', 6.0, 0.00051]
72 ['61030123', None, 'C0000009308', 'M44761', 'null', 'null', 'null', 6.0, 0.00015099999999999998]
73 ['61030123', None, 'C0000009308', 'M44030', 'null', 'null', 'null', 6.0, 0.00025]
74 ['61030123', None, 'C0000009308', 'C0000009258', 'M27839', 'null', 'null', 6.0, 1.0, 0.002646]
75 ['61030123', None, 'C0000009308', 'C0000009258', 'M37998', 'null', 'null', 6.0, 1.0, 5.4e-05]
76 ['61030123', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M25064', 'null', 6.0, 1.0, 1.0, 0.000372]
77 ['61030123', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M38272', 'null', 6.0, 1.0, 1.0, 0.004464]
78 ['61030123', None, 'C0000009308', 'C0000009258', 'C0000009243', 'M40443', 'null', 6.0, 1.0, 1.0, 0.004464]
79 ['61030123', None, 'P11212318', 'null', 'null', 'null', 'null', 12.0]
80 ['61030123', None, 'P11220267', 'null', 'null', 'null', 'null', 0.08566]
81 ['61030123', None, 'P11250855', 'null', 'null', 'null', 'null', 12.0]
82 ['61030123', None, 'P11242085', 'null', 'null', 'null', 'null', 1.0]
83 ['61030123', None, 'P11260167', 'null', 'null', 'null', 'null', 2.0]
84 ['61030123', None, 'P11270073', 'null', 'null', 'null', 'null', 0.0008100000000000001]
85 ['61030123', None, 'P11270120', 'null', 'null', 'null', 'null', 0.0044599999999999996]
86 ['61030123', None, 'P11270110', 'null', 'null', 'null', 'null', 0.0022299999999999998]
87 ['61030123', None, 'P11270195', 'null', 'null', 'null', 'null', 0.00135]
88 ['1051972', None, 'C0000005899', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
89 ['1051972', None, 'C0000005899', 'M18613', 'null', 'null', 'null', 24.0, 0.000224]
90 ['1051972', None, 'C0000005899', 'M17137', 'null', 'null', 'null', 24.0, 0.000311]
91 ['1051972', None, 'C0000005899', 'M43749', 'null', 'null', 'null', 24.0, 0.000249]
92 ['1051972', None, 'C0000005899', 'C0000005884', 'M33469', 'null', 'null', 24.0, 1.0, 0.001754]
93 ['1051972', None, 'C0000005899', 'C0000005884', 'M32079', 'null', 'null', 24.0, 1.0, 3.5000000000000004e-05]
94 ['1051972', None, 'C0000005899', 'C0000005884', 'C0000005864', 'M31520', 'null', 24.0, 1.0, 1.0, 0.01549]
95 ['1051972', None, 'C0000010544', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
96 ['1051972', None, 'C0000010544', 'M43783', 'null', 'null', 'null', 24.0, 0.000467]
97 ['1051972', None, 'C0000010544', 'M42142', 'null', 'null', 'null', 24.0, 0.000311]
98 ['1051972', None, 'C0000010544', 'C0000010526', 'M33469', 'null', 'null', 24.0, 1.0, 0.001754]
99 ['1051972', None, 'C0000010544', 'C0000010526', 'M27640', 'null', 'null', 24.0, 1.0, 3.5000000000000004e-05]
100 ['1051972', None, 'C0000010544', 'C0000010526', 'C0000010271', 'M40985', 'null', 24.0, 1.0, 1.0, 0.004695]
101 ['1051972', None, 'C0000010544', 'C0000010526', 'C0000010271', 'M31520', 'null', 24.0, 1.0, 1.0, 0.010955999999999999]
102 ['1051972', None, 'C0000005900', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
103 ['1051972', None, 'C0000005900', 'M18613', 'null', 'null', 'null', 24.0, 0.000224]
104 ['1051972', None, 'C0000005900', 'M17137', 'null', 'null', 'null', 24.0, 0.000311]
105 ['1051972', None, 'C0000005900', 'M43749', 'null', 'null', 'null', 24.0, 0.000249]
106 ['1051972', None, 'C0000005900', 'C0000005885', 'M33469', 'null', 'null', 24.0, 1.0, 0.001754]
107 ['1051972', None, 'C0000005900', 'C0000005885', 'M34871', 'null', 'null', 24.0, 1.0, 3.5000000000000004e-05]
108 ['1051972', None, 'C0000005900', 'C0000005885', 'C0000005864', 'M31520', 'null', 24.0, 1.0, 1.0, 0.01549]
109 ['1051972', None, 'C0000010545', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
110 ['1051972', None, 'C0000010545', 'M20688', 'null', 'null', 'null', 24.0, 0.000467]
111 ['1051972', None, 'C0000010545', 'M21965', 'null', 'null', 'null', 24.0, 0.000311]
112 ['1051972', None, 'C0000010545', 'C0000010525', 'M33469', 'null', 'null', 24.0, 1.0, 0.001754]
113 ['1051972', None, 'C0000010545', 'C0000010525', 'M28931', 'null', 'null', 24.0, 1.0, 3.5000000000000004e-05]
114 ['1051972', None, 'C0000010545', 'C0000010525', 'C0000010271', 'M40985', 'null', 24.0, 1.0, 1.0, 0.004695]
115 ['1051972', None, 'C0000010545', 'C0000010525', 'C0000010271', 'M31520', 'null', 24.0, 1.0, 1.0, 0.010955999999999999]
116 ['1051972', None, 'C0000005901', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
117 ['1051972', None, 'C0000005901', 'M18613', 'null', 'null', 'null', 24.0, 0.000224]
118 ['1051972', None, 'C0000005901', 'M17137', 'null', 'null', 'null', 24.0, 0.000311]
119 ['1051972', None, 'C0000005901', 'M43749', 'null', 'null', 'null', 24.0, 0.000249]
120 ['1051972', None, 'C0000005901', 'C0000005886', 'M32455', 'null', 'null', 24.0, 1.0, 5.2e-05]
121 ['1051972', None, 'C0000005901', 'C0000005886', 'M33469', 'null', 'null', 24.0, 1.0, 0.001737]
122 ['1051972', None, 'C0000005901', 'C0000005886', 'C0000005864', 'M31520', 'null', 24.0, 1.0, 1.0, 0.01549]
123 ['1051972', None, 'C0000010546', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
124 ['1051972', None, 'C0000010546', 'M43786', 'null', 'null', 'null', 24.0, 0.000467]
125 ['1051972', None, 'C0000010546', 'M46637', 'null', 'null', 'null', 24.0, 0.000311]
126 ['1051972', None, 'C0000010546', 'C0000010524', 'M33469', 'null', 'null', 24.0, 1.0, 0.001718]
127 ['1051972', None, 'C0000010546', 'C0000010524', 'M44307', 'null', 'null', 24.0, 1.0, 7.099999999999999e-05]
128 ['1051972', None, 'C0000010546', 'C0000010524', 'C0000010271', 'M40985', 'null', 24.0, 1.0, 1.0, 0.004695]
129 ['1051972', None, 'C0000010546', 'C0000010524', 'C0000010271', 'M31520', 'null', 24.0, 1.0, 1.0, 0.010955999999999999]
130 ['1051972', None, 'C0000005902', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
131 ['1051972', None, 'C0000005902', 'M18613', 'null', 'null', 'null', 24.0, 0.000224]
132 ['1051972', None, 'C0000005902', 'M17137', 'null', 'null', 'null', 24.0, 0.000311]
133 ['1051972', None, 'C0000005902', 'M43749', 'null', 'null', 'null', 24.0, 0.000249]
134 ['1051972', None, 'C0000005902', 'C0000005887', 'M22710', 'null', 'null', 24.0, 1.0, 5.2e-05]
135 ['1051972', None, 'C0000005902', 'C0000005887', 'M33469', 'null', 'null', 24.0, 1.0, 0.001737]
136 ['1051972', None, 'C0000005902', 'C0000005887', 'C0000005864', 'M31520', 'null', 24.0, 1.0, 1.0, 0.01549]
137 ['1051972', None, 'C0000010547', 'M22411', 'null', 'null', 'null', 24.0, 7.4e-05]
138 ['1051972', None, 'C0000010547', 'M30710', 'null', 'null', 'null', 24.0, 0.000467]
139 ['1051972', None, 'C0000010547', 'M20676', 'null', 'null', 'null', 24.0, 0.000311]
140 ['1051972', None, 'C0000010547', 'C0000010523', 'M33469', 'null', 'null', 24.0, 1.0, 0.001737]
141 ['1051972', None, 'C0000010547', 'C0000010523', 'M29142', 'null', 'null', 24.0, 1.0, 5.2e-05]
142 ['1051972', None, 'C0000010547', 'C0000010523', 'C0000010271', 'M40985', 'null', 24.0, 1.0, 1.0, 0.004695]
143 ['1051972', None, 'C0000010547', 'C0000010523', 'C0000010271', 'M31520', 'null', 24.0, 1.0, 1.0, 0.010955999999999999]
144 ['1051972', None, 'P11270079', 'null', 'null', 'null', 'null', 0.0378]
145 ['1051972', None, 'P11230073', 'null', 'null', 'null', 'null', 12.0]
146 ['1051972', None, 'P11240910', 'null', 'null', 'null', 'null', 1.0]
147 ['1051972', None, 'P11270073', 'null', 'null', 'null', 'null', 0.0009739999999999999]
148 ['1051972', None, 'P11211979', 'null', 'null', 'null', 'null', 96.0]
149 ['1051972', None, 'P11220274', 'null', 'null', 'null', 'null', 0.41264]
150 ['1051972', None, 'P11250385', 'null', 'null', 'null', 'null', 12.0]
151 ['168743', None, 'C0000010019', 'M22462', 'null', 'null', 'null', 18.0, 5e-06]
152 ['168743', None, 'C0000010019', 'M45117', 'null', 'null', 'null', 18.0, 0.000214]
153 ['168743', None, 'C0000010019', 'M45426', 'null', 'null', 'null', 18.0, 0.000503]
154 ['168743', None, 'C0000010019', 'M45424', 'null', 'null', 'null', 18.0, 0.000316]
155 ['168743', None, 'C0000010019', 'M42025', 'null', 'null', 'null', 18.0, 0.000331]
156 ['168743', None, 'C0000010019', 'C0000009995', 'M38273', 'null', 'null', 18.0, 1.0, 0.003044]
157 ['168743', None, 'C0000010019', 'C0000009995', 'M19934', 'null', 'null', 18.0, 1.0, 6.2e-05]
158 ['168743', None, 'C0000010019', 'C0000009995', 'M37958', 'null', 'null', 18.0, 1.0, 0.001294]
159 ['168743', None, 'C0000010019', 'C0000009995', 'M40239', 'null', 'null', 18.0, 1.0, 5.4e-05]
160 ['168743', None, 'C0000010019', 'C0000009995', 'M41908', 'null', 'null', 18.0, 1.0, 0.006813]
161 ['168743', None, 'C0000010019', 'C0000009995', 'M45234', 'null', 'null', 18.0, 1.0, 0.000406]
162 ['168743', None, 'C0000010019', 'C0000009995', 'M43203', 'null', 'null', 18.0, 1.0, 0.00292]
163 ['168743', None, 'C0000010019', 'C0000009964', 'M40239', 'null', 'null', 18.0, 1.0, 1.3e-05]
164 ['168743', None, 'C0000010019', 'C0000009964', 'M21905', 'null', 'null', 18.0, 1.0, 0.000311]
165 ['168743', None, 'C0000010019', 'C0000009964', 'M19934', 'null', 'null', 18.0, 1.0, 6e-06]
166 ['168743', None, 'C0000010019', 'C0000009964', 'M43203', 'null', 'null', 18.0, 1.0, 0.00029]
167 ['168743', None, 'C0000010020', 'M22462', 'null', 'null', 'null', 18.0, 5e-06]
168 ['168743', None, 'C0000010020', 'M45117', 'null', 'null', 'null', 18.0, 0.000214]
169 ['168743', None, 'C0000010020', 'M45426', 'null', 'null', 'null', 18.0, 0.000503]
170 ['168743', None, 'C0000010020', 'M45424', 'null', 'null', 'null', 18.0, 0.000316]
171 ['168743', None, 'C0000010020', 'M42025', 'null', 'null', 'null', 18.0, 0.000331]
172 ['168743', None, 'C0000010020', 'C0000009994', 'M38273', 'null', 'null', 18.0, 1.0, 0.003044]
173 ['168743', None, 'C0000010020', 'C0000009994', 'M19934', 'null', 'null', 18.0, 1.0, 6.2e-05]
174 ['168743', None, 'C0000010020', 'C0000009994', 'M37958', 'null', 'null', 18.0, 1.0, 0.001294]
175 ['168743', None, 'C0000010020', 'C0000009994', 'M40239', 'null', 'null', 18.0, 1.0, 5.4e-05]
176 ['168743', None, 'C0000010020', 'C0000009994', 'M45325', 'null', 'null', 18.0, 1.0, 0.000406]
177 ['168743', None, 'C0000010020', 'C0000009994', 'M41908', 'null', 'null', 18.0, 1.0, 0.006813]
178 ['168743', None, 'C0000010020', 'C0000009994', 'M43203', 'null', 'null', 18.0, 1.0, 0.00292]
179 ['168743', None, 'C0000010020', 'C0000009964', 'M40239', 'null', 'null', 18.0, 1.0, 1.3e-05]
180 ['168743', None, 'C0000010020', 'C0000009964', 'M21905', 'null', 'null', 18.0, 1.0, 0.000311]
181 ['168743', None, 'C0000010020', 'C0000009964', 'M19934', 'null', 'null', 18.0, 1.0, 6e-06]
182 ['168743', None, 'C0000010020', 'C0000009964', 'M43203', 'null', 'null', 18.0, 1.0, 0.00029]
183 ['168743', None, 'C0000010021', 'M22462', 'null', 'null', 'null', 18.0, 5e-06]
184 ['168743', None, 'C0000010021', 'M45117', 'null', 'null', 'null', 18.0, 0.000214]
185 ['168743', None, 'C0000010021', 'M45426', 'null', 'null', 'null', 18.0, 0.000503]
186 ['168743', None, 'C0000010021', 'M45424', 'null', 'null', 'null', 18.0, 0.000316]
187 ['168743', None, 'C0000010021', 'M42025', 'null', 'null', 'null', 18.0, 0.000331]
188 ['168743', None, 'C0000010021', 'C0000009993', 'M38273', 'null', 'null', 18.0, 1.0, 0.003044]
189 ['168743', None, 'C0000010021', 'C0000009993', 'M19934', 'null', 'null', 18.0, 1.0, 6.2e-05]
190 ['168743', None, 'C0000010021', 'C0000009993', 'M37958', 'null', 'null', 18.0, 1.0, 0.001294]
191 ['168743', None, 'C0000010021', 'C0000009993', 'M40239', 'null', 'null', 18.0, 1.0, 5.4e-05]
192 ['168743', None, 'C0000010021', 'C0000009993', 'M45322', 'null', 'null', 18.0, 1.0, 0.000406]
193 ['168743', None, 'C0000010021', 'C0000009993', 'M41908', 'null', 'null', 18.0, 1.0, 0.006813]
194 ['168743', None, 'C0000010021', 'C0000009993', 'M43203', 'null', 'null', 18.0, 1.0, 0.00292]
195 ['168743', None, 'C0000010021', 'C0000009964', 'M40239', 'null', 'null', 18.0, 1.0, 1.3e-05]
196 ['168743', None, 'C0000010021', 'C0000009964', 'M21905', 'null', 'null', 18.0, 1.0, 0.000311]
197 ['168743', None, 'C0000010021', 'C0000009964', 'M19934', 'null', 'null', 18.0, 1.0, 6e-06]
198 ['168743', None, 'C0000010021', 'C0000009964', 'M43203', 'null', 'null', 18.0, 1.0, 0.00029]
199 ['168743', None, 'C0000010022', 'M22462', 'null', 'null', 'null', 18.0, 5e-06]
200 ['168743', None, 'C0000010022', 'M45117', 'null', 'null', 'null', 18.0, 0.000214]
201 ['168743', None, 'C0000010022', 'M45426', 'null', 'null', 'null', 18.0, 0.000503]
202 ['168743', None, 'C0000010022', 'M45424', 'null', 'null', 'null', 18.0, 0.000316]
203 ['168743', None, 'C0000010022', 'M42025', 'null', 'null', 'null', 18.0, 0.000331]
204 ['168743', None, 'C0000010022', 'C0000009992', 'M38273', 'null', 'null', 18.0, 1.0, 0.003044]
205 ['168743', None, 'C0000010022', 'C0000009992', 'M19934', 'null', 'null', 18.0, 1.0, 6.2e-05]
206 ['168743', None, 'C0000010022', 'C0000009992', 'M37958', 'null', 'null', 18.0, 1.0, 0.001294]
207 ['168743', None, 'C0000010022', 'C0000009992', 'M40239', 'null', 'null', 18.0, 1.0, 5.4e-05]
208 ['168743', None, 'C0000010022', 'C0000009992', 'M45324', 'null', 'null', 18.0, 1.0, 0.000406]
209 ['168743', None, 'C0000010022', 'C0000009992', 'M41908', 'null', 'null', 18.0, 1.0, 0.006813]
210 ['168743', None, 'C0000010022', 'C0000009992', 'M43203', 'null', 'null', 18.0, 1.0, 0.00292]
211 ['168743', None, 'C0000010022', 'C0000009964', 'M40239', 'null', 'null', 18.0, 1.0, 1.3e-05]

In [100]:
# Convert the dictionary to a list of lists with padding
max_length = max(len(row) for row in BOMtree_transformed.values())
data_list = [row + [None] * (max_length - len(row)) for row in BOMtree_transformed.values()]

# Create a DataFrame from the list of lists
BOMtree_transformed = pd.DataFrame(data_list)

# Reset column names (optional)
BOMtree_transformed.columns = ['SKU', '3****', 'C toothbrush', 'C HDL', 'C HDL S.1', 'Raw Material','ratio2','ratio3','ratio4','ratio5','ratio6']

BOMtree_transformed.replace({None: 'null', np.nan: 'null'}, inplace=True)

In [101]:
BOMtree_transformed

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,ratio6
0,VN01289A,null,C0000009305,M22411,null,null,null,18.000000,0.000076,null,null
1,VN01289A,null,C0000009305,M44034,null,null,null,18.000000,0.00051,null,null
2,VN01289A,null,C0000009305,M44761,null,null,null,18.000000,0.000151,null,null
3,VN01289A,null,C0000009305,M44030,null,null,null,18.000000,0.00025,null,null
4,VN01289A,null,C0000009305,C0000009257,M27839,null,null,18.000000,1.0,0.002646,null
...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,P11241721,null,null,null,null,1.000000,null,null,null
13506,FVN00156,null,P11270073,null,null,null,null,0.000900,null,null,null
13507,FVN00156,null,P11270120,null,null,null,null,0.012500,null,null,null
13508,FVN00156,null,P11270110,null,null,null,null,0.006188,null,null,null
13509,FVN00156,null,P11270195,null,null,null,null,0.003160,null,null,null

### MOVE P,M TO THE LAST

In [102]:
def reposition_last_value(data_range, last_column_name):
    for idx in range(len(data_range)):
        row = data_range.iloc[idx]
        if row[last_column_name] != "null":
            continue  # Skip rows where the last column is not 'null'
        
        last_value = "null"
        last_column = "null"
        for col in reversed(data_range.columns):
            if row[col] != "null":
                last_value = row[col]
                last_column = col
                data_range.iat[idx, data_range.columns.get_loc(col)] = "null"
                break
        if last_value != "null" and last_column != "null":
            data_range.iat[idx, data_range.columns.get_loc(last_column_name)] = last_value
            data_range.iat[idx, data_range.columns.get_loc(last_column)] = "null"

# Assuming BOMtree_transformed_test is a DataFrame
BOMtree_transformed1 = BOMtree_transformed.iloc[:, :6]
BOMtree_transformed2 = BOMtree_transformed.iloc[:, 6:]
reposition_last_value(BOMtree_transformed1, 'Raw Material')
reposition_last_value(BOMtree_transformed2, 'ratio6')

In [103]:
# Assuming BOMtree_transformed_test1 and BOMtree_transformed_test2 are your DataFrames
BOMtree_transformed_layouted = pd.concat([BOMtree_transformed1, BOMtree_transformed2], axis=1)

# If you want to reset the index of the resulting DataFrame, you can do:
BOMtree_transformed_layouted = BOMtree_transformed_layouted.reset_index(drop=True)

# The resulting DataFrame (expanded_dataframe) will have columns from both input DataFrames side by side.
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,ratio6
0,VN01289A,null,C0000009305,null,null,M22411,null,18.0,null,null,0.000076
1,VN01289A,null,C0000009305,null,null,M44034,null,18.0,null,null,0.00051
2,VN01289A,null,C0000009305,null,null,M44761,null,18.0,null,null,0.000151
3,VN01289A,null,C0000009305,null,null,M44030,null,18.0,null,null,0.00025
4,VN01289A,null,C0000009305,C0000009257,null,M27839,null,18.0,1.0,null,0.002646
...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,null,null,null,P11241721,null,null,null,null,1.0
13506,FVN00156,null,null,null,null,P11270073,null,null,null,null,0.0009
13507,FVN00156,null,null,null,null,P11270120,null,null,null,null,0.0125
13508,FVN00156,null,null,null,null,P11270110,null,null,null,null,0.006188
13509,FVN00156,null,null,null,null,P11270195,null,null,null,null,0.00316

### DEAL WITH HANDLE

In [104]:
df_list_handle = pd.read_csv(folder_path + "List Handle.csv", delimiter=',')
df_list_handle['SKU'] = df_list_handle['SKU'].astype(str)
df_list_handle = df_list_handle['SKU'].tolist()
df_list_handle

['1050458',
 '1050459',
 '1050460',
 '1050461',
 '61030124',
 '61030125',
 '61030126',
 '61030127',
 '61037835',
 '61037836']

In [105]:
for index, row in BOMtree_transformed_layouted.iterrows():
    if row['SKU'] in df_list_handle:
        BOMtree_transformed_layouted.at[index, 'C HDL S.1'] = row['C HDL']
        BOMtree_transformed_layouted.at[index, 'C HDL'] = row['C toothbrush']
        BOMtree_transformed_layouted.at[index, 'C toothbrush'] = 'null'
        BOMtree_transformed_layouted.at[index, 'ratio5'] = row['ratio4']
        BOMtree_transformed_layouted.at[index, 'ratio4'] = row['ratio3']
        BOMtree_transformed_layouted.at[index, 'ratio3'] = 'null'

In [106]:
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,ratio6
0,VN01289A,null,C0000009305,null,null,M22411,null,18.0,null,null,0.000076
1,VN01289A,null,C0000009305,null,null,M44034,null,18.0,null,null,0.00051
2,VN01289A,null,C0000009305,null,null,M44761,null,18.0,null,null,0.000151
3,VN01289A,null,C0000009305,null,null,M44030,null,18.0,null,null,0.00025
4,VN01289A,null,C0000009305,C0000009257,null,M27839,null,18.0,1.0,null,0.002646
...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,null,null,null,P11241721,null,null,null,null,1.0
13506,FVN00156,null,null,null,null,P11270073,null,null,null,null,0.0009
13507,FVN00156,null,null,null,null,P11270120,null,null,null,null,0.0125
13508,FVN00156,null,null,null,null,P11270110,null,null,null,null,0.006188
13509,FVN00156,null,null,null,null,P11270195,null,null,null,null,0.00316

In [107]:
BOMtree_transformed_layouted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13510 entries, 0 to 13509
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SKU           13510 non-null  object
 1   3****         13510 non-null  object
 2   C toothbrush  13510 non-null  object
 3   C HDL         13510 non-null  object
 4   C HDL S.1     13510 non-null  object
 5   Raw Material  13510 non-null  object
 6   ratio2        13510 non-null  object
 7   ratio3        13510 non-null  object
 8   ratio4        13510 non-null  object
 9   ratio5        13510 non-null  object
 10  ratio6        13510 non-null  object
dtypes: object(11)
memory usage: 1.1+ MB

## 3.8 ADD INFORMATION OF P,M

In [108]:
BOMtree_temp = BOMtree
BOMtree_temp

            lv1          lv2          lv3     lv4   lv5   lv6
65     VN01289A  C0000009305       M22411    null  null  null
66     VN01289A  C0000009305       M44034    null  null  null
67     VN01289A  C0000009305       M44761    null  null  null
68     VN01289A  C0000009305       M44030    null  null  null
69     VN01289A  C0000009305  C0000009257  M27839  null  null
...         ...          ...          ...     ...   ...   ...
28668  FVN00156    P11241721         null    null  null  null
28669  FVN00156    P11270073         null    null  null  null
28670  FVN00156    P11270120         null    null  null  null
28671  FVN00156    P11270110         null    null  null  null
28672  FVN00156    P11270195         null    null  null  null

[13510 rows x 6 columns]

In [109]:
BOMtree_transformed_layouted = pd.merge(BOMtree_transformed_layouted, df[["Component",'Component Description','Component UOM']].drop_duplicates(subset=["Component"], keep="first"), how='left', left_on=['Raw Material'], right_on=['Component'])
# Drop 'Material' and 'Component' columns
BOMtree_transformed_layouted = BOMtree_transformed_layouted.drop(columns=['Component'])
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,ratio6,Component Description,Component UOM
0,VN01289A,null,C0000009305,null,null,M22411,null,18.0,null,null,0.000076,Hongfeng Aluminum 1.3X0.28MM anchor wire,KG
1,VN01289A,null,C0000009305,null,null,M44034,null,18.0,null,null,0.00051,K.R. PBT NONTAPER BLUE 305S 0.203MM/8MIL,KG
2,VN01289A,null,C0000009305,null,null,M44761,null,18.0,null,null,0.000151,K.R. PBT GREEN 328S 0.203MM/8MIL,KG
3,VN01289A,null,C0000009305,null,null,M44030,null,18.0,null,null,0.00025,K.R. PBT NONTAPER WHITE102S 0.203MM/8MIL,KG
4,VN01289A,null,C0000009305,C0000009257,null,M27839,null,18.0,1.0,null,0.002646,DONGGUAN TOP POLYMER 8201-601B0150004TPE,KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,null,null,null,P11241721,null,null,null,null,1.0,EC 19 rPP FHM SHIPPER 1PK 48 LATAM,ST
13506,FVN00156,null,null,null,null,P11270073,null,null,null,null,0.0009,OPP TAPE WITH LOGO-910m,ROL
13507,FVN00156,null,null,null,null,P11270120,null,null,null,null,0.0125,Slip Sheet 40x48 0.8MM,ST
13508,FVN00156,null,null,null,null,P11270110,null,null,null,null,0.006188,STRETCH WRAP FILM WIDTH ROLL 500MM 14KG,KG
13509,FVN00156,null,null,null,null,P11270195,null,null,null,null,0.00316,STRETCH WRAP FILM 12 MIC ROLL 500MM 14KG,KG

In [110]:
### new SKU

## 3.9 FILTER OUT LIST ONLY CHANGE QUANTITY

In [111]:
df_ecn_filtered

,Material,Component,Change no.,chng no. to,CmpValidFr,cmpValidTo,New/old Material
326,312272,C0000005899,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
327,312272,C0000010544,500000028368,NaN,04/17/2024,12/31/9999,C0000005899 - C0000005900 - C0000005901 - C000...
328,312272,C0000005900,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
329,312272,C0000010545,500000028368,NaN,04/17/2024,12/31/9999,C0000005899 - C0000005900 - C0000005901 - C000...
330,312272,C0000005901,NaN,500000028368,03/10/2023,04/17/2024,C0000010544 - C0000010545 - C0000010546 - C000...
...,...,...,...,...,...,...,...
29323,VN01129A,C0000010371,500000029326,NaN,11/26/2023,12/31/9999,C0000005930 - C0000005931 - C0000005932 - C000...
29327,VN01129A,P11270110,NaN,500000028821,02/14/2019,10/27/2023,P11270195
29328,VN01129A,P11270195,500000028821,NaN,10/27/2023,12/31/9999,P11270110
29460,VN01267A,P11270110,500000016876,500000028822,10/23/2018,10/27/2023,P11270195
29461,VN01267A,P11270195,500000028822,NaN,10/27/2023,12/31/9999,P11270110

In [112]:
df_change_quantity = df_ecn_filtered[df_ecn_filtered.duplicated(subset=['Material', 'Component'], keep=False)]
df_change_quantity.head()

,Material,Component,Change no.,chng no. to,CmpValidFr,cmpValidTo,New/old Material
12096,1053201,P11220265,500000014726,500000028314,05/08/2018,11/27/2023,P11212507 - P11220265 - P11270073
12097,1053201,P11220265,500000028314,NaN,11/27/2023,12/31/9999,P11211905 - P11220265 - P11270073
12100,1053201,P11270073,500000022195,500000028314,10/09/2020,11/27/2023,P11212507 - P11220265 - P11270073
12101,1053201,P11270073,500000028314,NaN,11/27/2023,12/31/9999,P11211905 - P11220265 - P11270073
16912,61016707,P11220274,500000023327,500000028925,07/12/2021,10/30/2023,P11212531 - P11220274

In [113]:
df_ecn_filtered = df_ecn_filtered.drop_duplicates(subset=['Material', 'Component'], keep=False)
len(df_ecn_filtered)

1098

## 3.10 ADD NEW MATERIAL

In [114]:
df_ecn_new_material = df_ecn_filtered[['Material','Component','New/old Material']]
df_ecn_new_material

,Material,Component,New/old Material
326,312272,C0000005899,C0000010544 - C0000010545 - C0000010546 - C000...
327,312272,C0000010544,C0000005899 - C0000005900 - C0000005901 - C000...
328,312272,C0000005900,C0000010544 - C0000010545 - C0000010546 - C000...
329,312272,C0000010545,C0000005899 - C0000005900 - C0000005901 - C000...
330,312272,C0000005901,C0000010544 - C0000010545 - C0000010546 - C000...
...,...,...,...
29323,VN01129A,C0000010371,C0000005930 - C0000005931 - C0000005932 - C000...
29327,VN01129A,P11270110,P11270195
29328,VN01129A,P11270195,P11270110
29460,VN01267A,P11270110,P11270195
29461,VN01267A,P11270195,P11270110

In [115]:
BOMtree_temp = BOMtree

In [116]:
def left_merge_dataframes_new_material(left_col1, left_col2):
    global BOMtree_temp
    
    result_df = pd.merge(BOMtree_temp, df_ecn_new_material, how='left', left_on=[left_col1, left_col2], right_on=['Material', 'Component'])
    
    # Drop 'Material' and 'Component' columns
    result_df = result_df.drop(columns=['Material', 'Component'])
    
    # Rename columns with suffixes based on the input column names
    result_df = result_df.rename(columns={
        'New/old Material': 'New/old Material_' + left_col2
    })
    
    BOMtree_temp = result_df  # Update the global variable
    return BOMtree_temp

# Call the function for each pair of columns
left_merge_dataframes_new_material('lv1', 'lv2')
left_merge_dataframes_new_material('lv2', 'lv3')
left_merge_dataframes_new_material('lv3', 'lv4')
left_merge_dataframes_new_material('lv4', 'lv5')
left_merge_dataframes_new_material('lv5', 'lv6')

,lv1,lv2,lv3,lv4,lv5,lv6,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6
0,VN01289A,C0000009305,M22411,null,null,null,NaN,NaN,NaN,NaN,NaN
1,VN01289A,C0000009305,M44034,null,null,null,NaN,NaN,NaN,NaN,NaN
2,VN01289A,C0000009305,M44761,null,null,null,NaN,NaN,NaN,NaN,NaN
3,VN01289A,C0000009305,M44030,null,null,null,NaN,NaN,NaN,NaN,NaN
4,VN01289A,C0000009305,C0000009257,M27839,null,null,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,P11241721,null,null,null,null,NaN,NaN,NaN,NaN,NaN
13506,FVN00156,P11270073,null,null,null,null,NaN,NaN,NaN,NaN,NaN
13507,FVN00156,P11270120,null,null,null,null,NaN,NaN,NaN,NaN,NaN
13508,FVN00156,P11270110,null,null,null,null,P11270195,NaN,NaN,NaN,NaN
13509,FVN00156,P11270195,null,null,null,null,P11270110,NaN,NaN,NaN,NaN

In [117]:
df_new_material_temp = BOMtree_temp[['New/old Material_lv2','New/old Material_lv3','New/old Material_lv4','New/old Material_lv5','New/old Material_lv6']]
df_new_material_temp

,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
13505,NaN,NaN,NaN,NaN,NaN
13506,NaN,NaN,NaN,NaN,NaN
13507,NaN,NaN,NaN,NaN,NaN
13508,P11270195,NaN,NaN,NaN,NaN
13509,P11270110,NaN,NaN,NaN,NaN

In [118]:
# Move material that not start with 3 to the right 1 column
mask = df_new_material_temp['New/old Material_lv2'].apply(lambda x: isinstance(x, str) and not x.startswith('3'))
df_new_material_temp.loc[mask, 'New/old Material_lv6'] = df_new_material_temp.loc[mask, 'New/old Material_lv5']
df_new_material_temp.loc[mask, 'New/old Material_lv5'] = df_new_material_temp.loc[mask, 'New/old Material_lv4']
df_new_material_temp.loc[mask, 'New/old Material_lv4'] = df_new_material_temp.loc[mask, 'New/old Material_lv3']
df_new_material_temp.loc[mask, 'New/old Material_lv3'] = df_new_material_temp.loc[mask, 'New/old Material_lv2']
df_new_material_temp.loc[mask, 'New/old Material_lv2'] = np.nan
df_new_material_temp

C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2987577924.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv6'] = df_new_material_temp.loc[mask, 'New/old Material_lv5']
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2987577924.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv5'] = df_new_material_temp.loc[mask, 'New/old Material_lv4']
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2987577924.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv4'] = df_new_material_temp.loc[mask, 'New/old Material_lv3']
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2987577924.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv3'] = df_new_material_temp.loc[mask, 'New/old Material_lv2']
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2987577924.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv2'] = np.nan

,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
13505,NaN,NaN,NaN,NaN,NaN
13506,NaN,NaN,NaN,NaN,NaN
13507,NaN,NaN,NaN,NaN,NaN
13508,NaN,P11270195,NaN,NaN,NaN
13509,NaN,P11270110,NaN,NaN,NaN

In [119]:
# Move starting with 'P' or 'M' to New/old Material_lv6
def assign_and_replace(column_name):
    # Create a copy of the DataFrame to avoid modifying the original data
    global df_new_material_temp

    # Assign values starting with 'P' or 'M' to New/old Material_lv6 and replace them with NaN in the specified column
    mask = df_new_material_temp[column_name].apply(lambda x: isinstance(x, str) and x.startswith(('P', 'M')))
    df_new_material_temp.loc[mask, 'New/old Material_lv6'] = df_new_material_temp.loc[mask, column_name].values
    df_new_material_temp.loc[mask, column_name] = np.nan

    return df_new_material_temp

In [120]:
# Move P, M to last column
assign_and_replace('New/old Material_lv3')
assign_and_replace('New/old Material_lv4')
assign_and_replace('New/old Material_lv5')

C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2594630325.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, 'New/old Material_lv6'] = df_new_material_temp.loc[mask, column_name].values
C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_11480\2594630325.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_material_temp.loc[mask, column_name] = np.nan

,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
13505,NaN,NaN,NaN,NaN,NaN
13506,NaN,NaN,NaN,NaN,NaN
13507,NaN,NaN,NaN,NaN,NaN
13508,NaN,NaN,NaN,NaN,P11270195
13509,NaN,NaN,NaN,NaN,P11270110

In [121]:
BOMtree_transformed_layouted = pd.concat([BOMtree_transformed_layouted, df_new_material_temp], axis=1)
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,ratio6,Component Description,Component UOM,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6
0,VN01289A,null,C0000009305,null,null,M22411,null,18.0,null,null,0.000076,Hongfeng Aluminum 1.3X0.28MM anchor wire,KG,NaN,NaN,NaN,NaN,NaN
1,VN01289A,null,C0000009305,null,null,M44034,null,18.0,null,null,0.00051,K.R. PBT NONTAPER BLUE 305S 0.203MM/8MIL,KG,NaN,NaN,NaN,NaN,NaN
2,VN01289A,null,C0000009305,null,null,M44761,null,18.0,null,null,0.000151,K.R. PBT GREEN 328S 0.203MM/8MIL,KG,NaN,NaN,NaN,NaN,NaN
3,VN01289A,null,C0000009305,null,null,M44030,null,18.0,null,null,0.00025,K.R. PBT NONTAPER WHITE102S 0.203MM/8MIL,KG,NaN,NaN,NaN,NaN,NaN
4,VN01289A,null,C0000009305,C0000009257,null,M27839,null,18.0,1.0,null,0.002646,DONGGUAN TOP POLYMER 8201-601B0150004TPE,KG,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,null,null,null,P11241721,null,null,null,null,1.0,EC 19 rPP FHM SHIPPER 1PK 48 LATAM,ST,NaN,NaN,NaN,NaN,NaN
13506,FVN00156,null,null,null,null,P11270073,null,null,null,null,0.0009,OPP TAPE WITH LOGO-910m,ROL,NaN,NaN,NaN,NaN,NaN
13507,FVN00156,null,null,null,null,P11270120,null,null,null,null,0.0125,Slip Sheet 40x48 0.8MM,ST,NaN,NaN,NaN,NaN,NaN
13508,FVN00156,null,null,null,null,P11270110,null,null,null,null,0.006188,STRETCH WRAP FILM WIDTH ROLL 500MM 14KG,KG,NaN,NaN,NaN,NaN,P11270195
13509,FVN00156,null,null,null,null,P11270195,null,null,null,null,0.00316,STRETCH WRAP FILM 12 MIC ROLL 500MM 14KG,KG,NaN,NaN,NaN,NaN,P11270110

In [122]:
# Move to match position as relayout
for index, row in BOMtree_transformed_layouted.iterrows():
    if row['SKU'] in df_list_handle:
        BOMtree_transformed_layouted.at[index, 'New/old Material_lv5'] = row['New/old Material_lv4']
        BOMtree_transformed_layouted.at[index, 'New/old Material_lv4'] = row['New/old Material_lv3']
        BOMtree_transformed_layouted.at[index, 'New/old Material_lv3'] = row['New/old Material_lv2']

## 3.11 ADD CHANGE INFORMATION

In [123]:
BOMtree_temp = BOMtree

In [124]:
def left_join_with_concat_rename(input_column):
    global BOMtree_temp, df_ecn_filtered

    # Create a temporary DataFrame with the required columns from filtered_df_ecn1
    df_ecn_temp = df_ecn_filtered[['Material', 'Component', input_column]]

    # Perform left join and overwrite BOMtree_transformed_layouted
    for i in range(5):
        left_col = BOMtree_temp.columns[i]
        right_col = BOMtree_temp.columns[i + 1]

        # Calculate the new column name based on the current 'i'
        new_col_name = f'{input_column}{i + 2}'

        # Rename the input column in df_ecn_temp
        df_ecn_temp.columns = ['Material', 'Component', new_col_name]
        BOMtree_temp = pd.merge(BOMtree_temp, df_ecn_temp,
                                        left_on=[left_col, right_col],
                                        right_on=['Material', 'Component'],
                                        how='left')

        # Drop the 'Material' and 'Component' columns from BOMtree_transformed2
        BOMtree_temp.drop(['Material', 'Component'], axis=1, inplace=True)
        
    #BOMtree_temp[input_column] = BOMtree_temp.iloc[:, -5:].astype(str).replace('nan', '').apply(lambda row: ' - '.join(row), axis=1)
    BOMtree_temp[input_column] = BOMtree_temp.iloc[:, -5:].astype(str).apply(lambda row: ' - '.join(row[row != 'nan']), axis=1)
    
    last_column_index = BOMtree_temp.columns.get_loc(BOMtree_temp.columns[-1])
    columns_to_delete = BOMtree_temp.columns[last_column_index - 5:last_column_index]
    BOMtree_temp = BOMtree_temp.drop(columns=columns_to_delete)
    
    return BOMtree_temp


left_join_with_concat_rename('Change no.')
left_join_with_concat_rename('chng no. to')
left_join_with_concat_rename('CmpValidFr')
left_join_with_concat_rename('cmpValidTo')

,lv1,lv2,lv3,lv4,lv5,lv6,Change no.,chng no. to,CmpValidFr,cmpValidTo
0,VN01289A,C0000009305,M22411,null,null,null,,,,
1,VN01289A,C0000009305,M44034,null,null,null,,,,
2,VN01289A,C0000009305,M44761,null,null,null,,,,
3,VN01289A,C0000009305,M44030,null,null,null,,,,
4,VN01289A,C0000009305,C0000009257,M27839,null,null,,,,
...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,P11241721,null,null,null,null,,,,
13506,FVN00156,P11270073,null,null,null,null,,,,
13507,FVN00156,P11270120,null,null,null,null,,,,
13508,FVN00156,P11270110,null,null,null,null,,500000028804,03/10/2023,10/27/2023
13509,FVN00156,P11270195,null,null,null,null,500000028804,,10/27/2023,12/31/9999

In [125]:
df_change_info_temp = BOMtree_temp[['Change no.','chng no. to','CmpValidFr','cmpValidTo']]
df_change_info_temp

         Change no.   chng no. to  CmpValidFr  cmpValidTo
0
1
2
3
4
...             ...           ...         ...         ...
13505
13506
13507
13508                500000028804  03/10/2023  10/27/2023
13509  500000028804                10/27/2023  12/31/9999

[13510 rows x 4 columns]

In [126]:
BOMtree_transformed_layouted = pd.concat([BOMtree_transformed_layouted, df_change_info_temp], axis=1)
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,...,Component UOM,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6,Change no.,chng no. to,CmpValidFr,cmpValidTo
0,VN01289A,null,C0000009305,null,null,M22411,null,18.0,null,null,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
1,VN01289A,null,C0000009305,null,null,M44034,null,18.0,null,null,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
2,VN01289A,null,C0000009305,null,null,M44761,null,18.0,null,null,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
3,VN01289A,null,C0000009305,null,null,M44030,null,18.0,null,null,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
4,VN01289A,null,C0000009305,C0000009257,null,M27839,null,18.0,1.0,null,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,null,null,null,null,P11241721,null,null,null,null,...,ST,NaN,NaN,NaN,NaN,NaN,,,,
13506,FVN00156,null,null,null,null,P11270073,null,null,null,null,...,ROL,NaN,NaN,NaN,NaN,NaN,,,,
13507,FVN00156,null,null,null,null,P11270120,null,null,null,null,...,ST,NaN,NaN,NaN,NaN,NaN,,,,
13508,FVN00156,null,null,null,null,P11270110,null,null,null,null,...,KG,NaN,NaN,NaN,NaN,P11270195,,500000028804,03/10/2023,10/27/2023
13509,FVN00156,null,null,null,null,P11270195,null,null,null,null,...,KG,NaN,NaN,NaN,NaN,P11270110,500000028804,,10/27/2023,12/31/9999

In [127]:
# Replace null with empty string
columns_to_replace = ['3****', 'C toothbrush', 'C HDL', 'C HDL S.1', 'Raw Material','ratio2','ratio3','ratio4','ratio5','ratio6']
BOMtree_transformed_layouted[columns_to_replace] = BOMtree_transformed_layouted[columns_to_replace].replace('null', '')
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,...,Component UOM,New/old Material_lv2,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6,Change no.,chng no. to,CmpValidFr,cmpValidTo
0,VN01289A,,C0000009305,,,M22411,,18.0,,,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
1,VN01289A,,C0000009305,,,M44034,,18.0,,,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
2,VN01289A,,C0000009305,,,M44761,,18.0,,,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
3,VN01289A,,C0000009305,,,M44030,,18.0,,,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
4,VN01289A,,C0000009305,C0000009257,,M27839,,18.0,1.0,,...,KG,NaN,NaN,NaN,NaN,NaN,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,,,,,P11241721,,,,,...,ST,NaN,NaN,NaN,NaN,NaN,,,,
13506,FVN00156,,,,,P11270073,,,,,...,ROL,NaN,NaN,NaN,NaN,NaN,,,,
13507,FVN00156,,,,,P11270120,,,,,...,ST,NaN,NaN,NaN,NaN,NaN,,,,
13508,FVN00156,,,,,P11270110,,,,,...,KG,NaN,NaN,NaN,NaN,P11270195,,500000028804,03/10/2023,10/27/2023
13509,FVN00156,,,,,P11270195,,,,,...,KG,NaN,NaN,NaN,NaN,P11270110,500000028804,,10/27/2023,12/31/9999

In [128]:
BOMtree_transformed_layouted.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13510 entries, 0 to 13509
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SKU                    13510 non-null  object
 1   3****                  13510 non-null  object
 2   C toothbrush           13510 non-null  object
 3   C HDL                  13510 non-null  object
 4   C HDL S.1              13510 non-null  object
 5   Raw Material           13510 non-null  object
 6   ratio2                 13510 non-null  object
 7   ratio3                 13510 non-null  object
 8   ratio4                 13510 non-null  object
 9   ratio5                 13510 non-null  object
 10  ratio6                 13510 non-null  float64
 11  Component Description  13510 non-null  object
 12  Component UOM          13510 non-null  object
 13  New/old Material_lv2   1347 non-null   object
 14  New/old Material_lv3   3939 non-null   object
 15  New/old Material_lv4   0 non-null      object
 16  New/old Material_lv5   0 non-null      object
 17  New/old Material_lv6   544 non-null    object
 18  Change no.             13510 non-null  object
 19  chng no. to            13510 non-null  object
 20  CmpValidFr             13510 non-null  object
 21  cmpValidTo             13510 non-null  object
dtypes: float64(1), object(21)
memory usage: 2.9+ MB

# 4 CONTINUE WITH OTHERS

## 4.1 SKU MASTER
https://docs.google.com/spreadsheets/d/1U1yERDQXrvE4_NbK_GwVIVvruC3oxWM90gLre0b6i9E/edit#gid=874534676

In [129]:
skumaster = pd.read_csv(folder_path + "SNP Master SKU YTD.csv", delimiter=',')
skumaster.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VN SKU             1290 non-null   object
 1   Short Bundle Name  685 non-null    object
 2   Current Status     1290 non-null   object
dtypes: object(3)
memory usage: 30.4+ KB

In [130]:
#merge SKU master
BOMtree_transformed_layouted = BOMtree_transformed_layouted.merge(skumaster[['VN SKU', 'Short Bundle Name','Current Status']], how='left', left_on='SKU', right_on='VN SKU')
# BOMtree = BOMtree[(BOMtree["PLANT"] == 'VN11') & ~(BOMtree["PLANT_SP_MATL_STATUS"] == 'C5')]
# BOMtree = BOMtree[~(BOMtree["PLANT_SP_MATL_STATUS"] == 'C5')]
BOMtree_transformed_layouted = BOMtree_transformed_layouted.drop(columns=['VN SKU'])
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,ratio2,ratio3,ratio4,ratio5,...,New/old Material_lv3,New/old Material_lv4,New/old Material_lv5,New/old Material_lv6,Change no.,chng no. to,CmpValidFr,cmpValidTo,Short Bundle Name,Current Status
0,VN01289A,,C0000009305,,,M22411,,18.0,,,...,NaN,NaN,NaN,NaN,,,,,TA_21,Active
1,VN01289A,,C0000009305,,,M44034,,18.0,,,...,NaN,NaN,NaN,NaN,,,,,TA_21,Active
2,VN01289A,,C0000009305,,,M44761,,18.0,,,...,NaN,NaN,NaN,NaN,,,,,TA_21,Active
3,VN01289A,,C0000009305,,,M44030,,18.0,,,...,NaN,NaN,NaN,NaN,,,,,TA_21,Active
4,VN01289A,,C0000009305,C0000009257,,M27839,,18.0,1.0,,...,NaN,NaN,NaN,NaN,,,,,TA_21,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,,,,,P11241721,,,,,...,NaN,NaN,NaN,NaN,,,,,EC_22RPP,Active
13506,FVN00156,,,,,P11270073,,,,,...,NaN,NaN,NaN,NaN,,,,,EC_22RPP,Active
13507,FVN00156,,,,,P11270120,,,,,...,NaN,NaN,NaN,NaN,,,,,EC_22RPP,Active
13508,FVN00156,,,,,P11270110,,,,,...,NaN,NaN,NaN,P11270195,,500000028804,03/10/2023,10/27/2023,EC_22RPP,Active
13509,FVN00156,,,,,P11270195,,,,,...,NaN,NaN,NaN,P11270110,500000028804,,10/27/2023,12/31/9999,EC_22RPP,Active

In [131]:
# Define the conditions for the new column
conditions = [
    BOMtree_transformed_layouted['chng no. to'].str.contains('|'.join(map(str, ECN_no))),
    BOMtree_transformed_layouted['Change no.'].str.contains('|'.join(map(str, ECN_no)))
]

# Define the choices for the new column
choices = ['Old', 'New']

# Create the new column based on the conditions and choices
BOMtree_transformed_layouted['old/new filter'] = pd.Series(pd.NA, index=BOMtree_transformed_layouted.index)  # Initialize the column with empty values
BOMtree_transformed_layouted['old/new filter'] = pd.Series(
    pd.Categorical(
        np.select(conditions, choices, default=''),
        categories=choices + [''],  # Include an empty category
        ordered=False
    ),
    index=BOMtree_transformed_layouted.index
)

In [132]:
kid_Decal = pd.read_csv(folder_path + "List Decal.csv", delimiter='\t')
kidDecal = kid_Decal.drop_duplicates()
kidDecal.head()

      Bundle Kid
0   K6+_OCEAN_21
1      K5+_TANDY
2      K5+_TAPER
3  K6+_JUNGLE_21

In [133]:
def get_rm_mother_list(row, kidDecal):
    if row['Short Bundle Name'] in kidDecal['Bundle Kid'].values:
        if row['C HDL S.1'] != '':
            return row['C HDL S.1']
        elif row['C HDL'] != '':
            return row['C HDL']
        elif row['C toothbrush'] != '':
            return row['C toothbrush']
        else:
            return row['SKU']
    else:
        if row['C HDL'] != '':
            return row['C HDL']
        elif row['C toothbrush'] != '':
            return row['C toothbrush']
        else:
            return row['SKU']

BOMtree_transformed_layouted['RM mother list'] = BOMtree_transformed_layouted.apply(lambda row: get_rm_mother_list(row, kidDecal), axis=1)

# Remove the column
column_to_move = BOMtree_transformed_layouted.pop('RM mother list')

# Insert the column at the desired position (index 6 for the 7th column)
BOMtree_transformed_layouted.insert(6, 'RM mother list', column_to_move)

In [134]:
# Define the lambda function to apply the conditions
def pm_ratio(row):
    if (row['3****'] != '') and (row['C toothbrush'] == '') and (row['C HDL'] == '') and (row['C HDL S.1'] == ''):
        return row['ratio2']
    else:
        return row['ratio6']

# Create the new column based on the conditions
BOMtree_transformed_layouted['PM ratio'] = BOMtree_transformed_layouted.apply(lambda row: pm_ratio(row), axis=1)

# Assuming your DataFrame is named BOMtree_transformed_layouted
column_to_move1 = BOMtree_transformed_layouted.pop('PM ratio')  # Remove the column

# Insert the column at the desired position (index 6 for the 7th column)
BOMtree_transformed_layouted.insert(12, 'PM ratio', column_to_move1)

## 4.2 NPI MASTER
https://docs.google.com/spreadsheets/d/1wlDX4puFnH314pqBmGSEBziVFJ3uBv_9IciuHF8r-90/edit#gid=1694214072

In [135]:
npi = pd.read_csv(folder_path + "NPI Master.csv", delimiter=',')
npi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 36 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Date                                              352 non-null    object
 1   Division request                                  280 non-null    object
 2   Subs request                                      347 non-null    object
 3   NPI Code link                                     352 non-null    object
 4   NPI ID                                            352 non-null    int64
 5   Project Status                                    352 non-null    object
 6   Project name                                      352 non-null    object
 7   SKU number of project                             352 non-null    object
 8   New SKU                                           352 non-null    object
 9   Refer SKU                                         209 non-null    object
 10  Regular or Promotion                              350 non-null    object
 11  Yearly volume of new SKU (pcs)                    63 non-null     float64
 12  Additional or replacement  volume  (Y/N)          352 non-null    object
 13  1st shipment requested                            352 non-null    object
 14  Estimate/Actual 1st shipment                      352 non-null    object
 15  First shipment ETD week                           269 non-null    float64
 16  Last lot for old SKU /old AW                      88 non-null     object
 17  AW status in BEAT                                 339 non-null    object
 18  Prinproof approval                                339 non-null    object
 19  SAP BOM                                           339 non-null    object
 20  NPI approval FOLDER  link                         352 non-null    object
 21  Project status and any update (manual)            265 non-null    object
 22  [auto] NPI Status                                 309 non-null    object
 23  Bundle Name                                       285 non-null    object
 24  New Material                                      352 non-null    object
 25  New Mold request                                  256 non-null    object
 26  Mix-up level                                      344 non-null    object
 27  AW overal                                         352 non-null    object
 28  Project Type                                      352 non-null    object
 29  ECC checklist                                     101 non-null    object
 30  General name of the Project (if have >2 bundles)  126 non-null    object
 31  LInk to Asia file                                 345 non-null    object
 32  Update status link                                309 non-null    object
 33  Month request                                     345 non-null    float64
 34  Fix 1st shipment                                  59 non-null     object
 35  Unnamed: 35                                       0 non-null      float64
dtypes: float64(4), int64(1), object(31)
memory usage: 99.1+ KB

In [136]:
# Extract the date and time using regular expressions
npi['Estimate/Actual 1st shipment'] = npi['Estimate/Actual 1st shipment'].str[4:24]

# Convert the column to Timestamp
npi['Estimate/Actual 1st shipment'] = pd.to_datetime(npi['Estimate/Actual 1st shipment'], format='%b %d %Y %H:%M:%S')

In [137]:
# Convert today's date to a pandas Timestamp
today = pd.Timestamp(datetime.now().date())

# Calculate the date 50 days ago
days_ago = today - timedelta(days=30)

# Filter the DataFrame
filtered_npi = npi[(npi['Project Status'].isin(['Done', 'On-going'])) &
                   (npi['Estimate/Actual 1st shipment'] >= days_ago) &
                   ~(npi['New SKU'] == 'Not required') &
                   ~(npi['New SKU'] == '')]

filtered_npi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 4 to 351
Data columns (total 36 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Date                                              41 non-null     object
 1   Division request                                  30 non-null     object
 2   Subs request                                      41 non-null     object
 3   NPI Code link                                     41 non-null     object
 4   NPI ID                                            41 non-null     int64
 5   Project Status                                    41 non-null     object
 6   Project name                                      41 non-null     object
 7   SKU number of project                             41 non-null     object
 8   New SKU                                           41 non-null     object
 9   Refer SKU                                         31 non-null     object
 10  Regular or Promotion                              41 non-null     object
 11  Yearly volume of new SKU (pcs)                    10 non-null     float64
 12  Additional or replacement  volume  (Y/N)          41 non-null     object
 13  1st shipment requested                            41 non-null     object
 14  Estimate/Actual 1st shipment                      41 non-null     datetime64[ns]
 15  First shipment ETD week                           36 non-null     float64
 16  Last lot for old SKU /old AW                      21 non-null     object
 17  AW status in BEAT                                 41 non-null     object
 18  Prinproof approval                                41 non-null     object
 19  SAP BOM                                           41 non-null     object
 20  NPI approval FOLDER  link                         41 non-null     object
 21  Project status and any update (manual)            29 non-null     object
 22  [auto] NPI Status                                 36 non-null     object
 23  Bundle Name                                       25 non-null     object
 24  New Material                                      41 non-null     object
 25  New Mold request                                  37 non-null     object
 26  Mix-up level                                      41 non-null     object
 27  AW overal                                         41 non-null     object
 28  Project Type                                      41 non-null     object
 29  ECC checklist                                     41 non-null     object
 30  General name of the Project (if have >2 bundles)  19 non-null     object
 31  LInk to Asia file                                 34 non-null     object
 32  Update status link                                36 non-null     object
 33  Month request                                     34 non-null     float64
 34  Fix 1st shipment                                  30 non-null     object
 35  Unnamed: 35                                       0 non-null      float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(30)
memory usage: 11.9+ KB

In [138]:
#merge SKU master
BOMtree_transformed_layouted= BOMtree_transformed_layouted.merge(filtered_npi[['SKU number of project', 'New SKU']], how='left', left_on='SKU', right_on='SKU number of project')
BOMtree_transformed_layouted =BOMtree_transformed_layouted.drop(columns=['SKU number of project'])
BOMtree_transformed_layouted = BOMtree_transformed_layouted.rename(columns={'New SKU': 'New SKU NPI'})
BOMtree_transformed_layouted = BOMtree_transformed_layouted.merge(filtered_npi[['SKU number of project', 'New SKU']], how='left', left_on='SKU', right_on='New SKU')
BOMtree_transformed_layouted =BOMtree_transformed_layouted.drop(columns=['New SKU'])
BOMtree_transformed_layouted =BOMtree_transformed_layouted.rename(columns={'SKU number of project': 'Old SKU NPI'})
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,RM mother list,ratio2,ratio3,ratio4,...,New/old Material_lv6,Change no.,chng no. to,CmpValidFr,cmpValidTo,Short Bundle Name,Current Status,old/new filter,New SKU NPI,Old SKU NPI
0,VN01289A,,C0000009305,,,M22411,C0000009305,,18.0,,...,NaN,,,,,TA_21,Active,,NaN,NaN
1,VN01289A,,C0000009305,,,M44034,C0000009305,,18.0,,...,NaN,,,,,TA_21,Active,,NaN,NaN
2,VN01289A,,C0000009305,,,M44761,C0000009305,,18.0,,...,NaN,,,,,TA_21,Active,,NaN,NaN
3,VN01289A,,C0000009305,,,M44030,C0000009305,,18.0,,...,NaN,,,,,TA_21,Active,,NaN,NaN
4,VN01289A,,C0000009305,C0000009257,,M27839,C0000009257,,18.0,1.0,...,NaN,,,,,TA_21,Active,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,,,,,P11241721,FVN00156,,,,...,NaN,,,,,EC_22RPP,Active,,NaN,NaN
13506,FVN00156,,,,,P11270073,FVN00156,,,,...,NaN,,,,,EC_22RPP,Active,,NaN,NaN
13507,FVN00156,,,,,P11270120,FVN00156,,,,...,NaN,,,,,EC_22RPP,Active,,NaN,NaN
13508,FVN00156,,,,,P11270110,FVN00156,,,,...,P11270195,,500000028804,03/10/2023,10/27/2023,EC_22RPP,Active,Old,NaN,NaN
13509,FVN00156,,,,,P11270195,FVN00156,,,,...,P11270110,500000028804,,10/27/2023,12/31/9999,EC_22RPP,Active,New,NaN,NaN

## 4.3 LOST ALLOWANCE
df_marc[['MATERIAL', 'PLANT_SP_MATL_STATUS','PLANT','COMPONENT_SCRAP']]

In [139]:
BOMtree_transformed_layouted = BOMtree_transformed_layouted.merge(df_marc[['MATERIAL','COMPONENT_SCRAP']],how='left',left_on='Raw Material',right_on='MATERIAL')
BOMtree_transformed_layouted = BOMtree_transformed_layouted.drop(columns=['MATERIAL'])
BOMtree_transformed_layouted = BOMtree_transformed_layouted.rename(columns={'COMPONENT_SCRAP': 'LA (%)'})
BOMtree_transformed_layouted

,SKU,3****,C toothbrush,C HDL,C HDL S.1,Raw Material,RM mother list,ratio2,ratio3,ratio4,...,Change no.,chng no. to,CmpValidFr,cmpValidTo,Short Bundle Name,Current Status,old/new filter,New SKU NPI,Old SKU NPI,LA (%)
0,VN01289A,,C0000009305,,,M22411,C0000009305,,18.0,,...,,,,,TA_21,Active,,NaN,NaN,0.0
1,VN01289A,,C0000009305,,,M44034,C0000009305,,18.0,,...,,,,,TA_21,Active,,NaN,NaN,0.5
2,VN01289A,,C0000009305,,,M44761,C0000009305,,18.0,,...,,,,,TA_21,Active,,NaN,NaN,0.5
3,VN01289A,,C0000009305,,,M44030,C0000009305,,18.0,,...,,,,,TA_21,Active,,NaN,NaN,0.5
4,VN01289A,,C0000009305,C0000009257,,M27839,C0000009257,,18.0,1.0,...,,,,,TA_21,Active,,NaN,NaN,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13505,FVN00156,,,,,P11241721,FVN00156,,,,...,,,,,EC_22RPP,Active,,NaN,NaN,0.1
13506,FVN00156,,,,,P11270073,FVN00156,,,,...,,,,,EC_22RPP,Active,,NaN,NaN,2.0
13507,FVN00156,,,,,P11270120,FVN00156,,,,...,,,,,EC_22RPP,Active,,NaN,NaN,0.0
13508,FVN00156,,,,,P11270110,FVN00156,,,,...,,500000028804,03/10/2023,10/27/2023,EC_22RPP,Active,Old,NaN,NaN,3.0
13509,FVN00156,,,,,P11270195,FVN00156,,,,...,500000028804,,10/27/2023,12/31/9999,EC_22RPP,Active,New,NaN,NaN,3.0

## 4.4 PM BOM

In [140]:
P_RMfile = pd.read_csv(folder_path + "List P code RM.csv", delimiter=',')
P_RM = P_RMfile.drop_duplicates()
P_RM.head()

   P code RM
0  P11220259
1  P11220264
2  P11220265
3  P11220258
4  P11220288

In [141]:
# Filter BOMtree_transformed_layouted based on Raw Material starting with 'P' and not in P_RM
pmBOM = BOMtree_transformed_layouted[BOMtree_transformed_layouted['Raw Material'].str.startswith('P') & ~BOMtree_transformed_layouted['Raw Material'].isin(P_RM['P code RM']) & (BOMtree_transformed_layouted['old/new filter'] != "New")]

# Group by and aggregate to get the sum of PM ratio
pmBOM = pmBOM.groupby(['RM mother list', 'Raw Material', 'Component Description'], as_index=False)['PM ratio'].sum()

# Reset the index of pmBOM
pmBOM.reset_index(drop=True, inplace=True)

## 4.5 RM BOM

In [142]:
# Step 1: Filter rows based on the conditions
filtered_bom = BOMtree_transformed_layouted[
    (BOMtree_transformed_layouted['Raw Material'].str.startswith('P') == False) |
    (BOMtree_transformed_layouted['Raw Material'].isin(P_RM['P code RM']))
]

# Step 2: Select the desired columns
rmBOM = filtered_bom[['RM mother list', 'Raw Material', 'Component Description', 'ratio6']]

# Step 3: Drop duplicates based on the specified columns
rmBOM = rmBOM.drop_duplicates(subset=['RM mother list', 'Raw Material', 'Component Description', 'ratio6'])

# Now, rmBOM contains the desired data without affecting the original DataFrame.

In [144]:
rmBOM

,RM mother list,Raw Material,Component Description,ratio6
0,C0000009305,M22411,Hongfeng Aluminum 1.3X0.28MM anchor wire,0.000076
1,C0000009305,M44034,K.R. PBT NONTAPER BLUE 305S 0.203MM/8MIL,0.000510
2,C0000009305,M44761,K.R. PBT GREEN 328S 0.203MM/8MIL,0.000151
3,C0000009305,M44030,K.R. PBT NONTAPER WHITE102S 0.203MM/8MIL,0.000250
4,C0000009257,M27839,DONGGUAN TOP POLYMER 8201-601B0150004TPE,0.002646
...,...,...,...,...
13501,FVN00156,P11220274,PET ROLL 0.3x 273mm S6 HA,0.206320
13503,FVN00156,P11270079,SHRINK FILM-330mmx15mic-POF-0612,0.012600
13506,FVN00156,P11270073,OPP TAPE WITH LOGO-910m,0.000900
13507,FVN00156,P11270120,Slip Sheet 40x48 0.8MM,0.012500
13508,FVN00156,P11270110,STRETCH WRAP FILM WIDTH ROLL 500MM 14KG,0.006188

## 4.6 AW TRACKING
https://docs.google.com/spreadsheets/d/1_eGB4Rz8ga7QXenUqIrzsSqbz-pKY6VWRuxMeuSdJIw/edit#gid=754673594

In [145]:
awtracking = pd.read_csv(folder_path + "AW Tracking.csv", delimiter=',')
awtracking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 46 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Project                                      953 non-null    object
 1   Code link                                    953 non-null    object
 2   Division                                     868 non-null    object
 3   BUNDLES                                      953 non-null    object
 4   PACKING TYPE                                 953 non-null    object
 5   VN.SKU                                       953 non-null    object
 6   SUB.SKU                                      952 non-null    object
 7   DESCRIPTION of SKU (SNP)                     949 non-null    object
 8   Component                                    953 non-null    object
 9   Current P                                    953 non-null    object
 10  Description of P# code                       857 non-null    object
 11  Curent Supplier                              945 non-null    object
 12  New SKU                                      953 non-null    object
 13  New P                                        953 non-null    object
 14  P Description                                925 non-null    object
 15  Dimension                                    953 non-null    object
 16  Die-line                                     951 non-null    object
 17  Supplier                                     953 non-null    object
 18  1. P code (SAP)                              925 non-null    object
 19  AODOC request                                672 non-null    object
 20  2. Upload to Beat                            695 non-null    object
 21  3. Mechanical Review                         677 non-null    object
 22  4. Printer accept bundle/ Final AW           699 non-null    object
 23  5. Send PCPS                                 894 non-null    object
 24  6. Get Pre-press file from supplier          892 non-null    object
 25  7. Pre-press file approve                    893 non-null    object
 26  SAP BOM+ Inform master data team             883 non-null    object
 27  8. Actual Print proof from Supplier          885 non-null    object
 28  PCPS signed off (Supplier)                   882 non-null    object
 29  9. Send PP for MKT (SNP )                    546 non-null    object
 30  10. Approve print proof                      878 non-null    object
 31  11. Send sample supplier                     877 non-null    object
 32  12. Update sample for IQC                    878 non-null    object
 33  AW STATUS                                    953 non-null    object
 34  SKU STATUS                                   953 non-null    object
 35  Implement timing per NPI request (ECN date)  919 non-null    object
 36  MOC/eTT                                      11 non-null     object
 37  New Palletization                            2 non-null      object
 38  Pre-press file (KPI)                         714 non-null    object
 39  Print proof (KPI)                            889 non-null    object
 40  PQ need                                      66 non-null     object
 41  ECN# (PKG)                                   375 non-null    object
 42  Mix-up level (SNP)                           953 non-null    object
 43  Hard Copy completed (Thao)                   850 non-null    object
 44  Week update                                  0 non-null      float64
 45  ECN DATE ESTIMATION                          621 non-null    object
dtypes: float64(1), object(45)
memory usage: 342.6+ KB

In [146]:
# Extract the date and time using regular expressions
awtracking['ECN DATE ESTIMATION'] = awtracking['ECN DATE ESTIMATION'].str[4:24]

# Convert the column to Timestamp
awtracking['ECN DATE ESTIMATION'] = pd.to_datetime(awtracking['ECN DATE ESTIMATION'], format='%b %d %Y %H:%M:%S')

ValueError: time data '-2021' does not match format '%b %d %Y %H:%M:%S' (match)

In [147]:
# Convert today's date to a pandas Timestamp
today1 = pd.Timestamp(datetime.now().date())

# Calculate the date 1 days ago
days_ago1 = today1 - timedelta(days=1)

# awtracking['ECN DATE ESTIMATION'] = pd.to_datetime(awtracking['ECN DATE ESTIMATION'], format="%m-%d-%Y", errors='coerce')

# Filter the DataFrame
awtracking_filter = awtracking[~(awtracking['Project'] == '') &
                    (awtracking['ECN DATE ESTIMATION'] >= days_ago1)]

awtracking_col = awtracking_filter[['VN.SKU', 'Current P', 'New SKU', 'New P', 'ECN# (PKG)', 'ECN DATE ESTIMATION']].copy()

# awtracking 1090
awtracking_col

TypeError: '>=' not supported between instances of 'str' and 'Timestamp'

In [148]:
# # Convert today's date to a pandas Timestamp
# today1 = pd.Timestamp(datetime.now().date())

# # Calculate the date 1 days ago
# days_ago1 = today1 - timedelta(days=1)

# awtracking['ECN DATE ESTIMATION'] = pd.to_datetime(awtracking['ECN DATE ESTIMATION'], format="%m-%d-%Y", errors='coerce')

# # Filter the DataFrame
# awtracking_filter = awtracking[~(awtracking['Project'] == '') &
#                     (awtracking['ECN DATE ESTIMATION'] >= days_ago1)]

# awtracking_col = awtracking_filter[['VN.SKU', 'Current P', 'New SKU', 'New P', 'ECN# (PKG)', 'ECN DATE ESTIMATION']].copy()

# # awtracking 1090
# awtracking_col

## 4.7 NON AW TRACKING
https://docs.google.com/spreadsheets/d/1_eGB4Rz8ga7QXenUqIrzsSqbz-pKY6VWRuxMeuSdJIw/edit#gid=1597922860

In [149]:
nonawtracking = pd.read_csv(folder_path + "Non AW Tracking.csv", delimiter=',')
# Extract the date and time using regular expressions
nonawtracking['ECN DATE ESTIMATION'] = nonawtracking['ECN DATE ESTIMATION'].str[4:24]

# Convert the column to Timestamp
nonawtracking['ECN DATE ESTIMATION'] = pd.to_datetime(nonawtracking['ECN DATE ESTIMATION'], format='%b %d %Y %H:%M:%S')
nonawtracking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 14 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   VN.SKU                                       857 non-null    object
 1   SUB.SKU                                      857 non-null    object
 2   DESCRIPTION of SKU (SNP)                     857 non-null    object
 3   Component                                    834 non-null    object
 4   Current P                                    782 non-null    object
 5   Description of P# code                       786 non-null    object
 6   New SKU                                      856 non-null    object
 7   New P                                        779 non-null    object
 8   ECN# (PKG)                                   829 non-null    object
 9   Mix-up level (SNP)                           826 non-null    object
 10  Implement timing per NPI request (ECN date)  851 non-null    object
 11  Reason for change (SNP)                      855 non-null    object
 12  Check ECN                                    853 non-null    object
 13  ECN DATE ESTIMATION                          783 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(13)
memory usage: 93.9+ KB

In [150]:
# nonawtracking['ECN DATE ESTIMATION'] = pd.to_datetime(nonawtracking['ECN DATE ESTIMATION'], format="%m-%d-%Y", errors='coerce')
# Filter the DataFrame
nonawtracking_filter = nonawtracking[~(nonawtracking['VN.SKU'] == '') &
                    (nonawtracking['ECN DATE ESTIMATION'] >= days_ago1)]

nonawtracking_col = nonawtracking_filter[['VN.SKU', 'Current P', 'New SKU', 'New P', 'ECN# (PKG)', 'ECN DATE ESTIMATION']].copy()

# awtracking 1090
nonawtracking_col

,VN.SKU,Current P,New SKU,New P,ECN# (PKG),ECN DATE ESTIMATION
188,1050545,C0000009478,Not required,C0000010385,500000027058,2023-10-31
189,1050545,C0000009479,Not required,C0000010386,500000027058,2023-10-31
190,1050545,C0000009480,Not required,C0000010387,500000027058,2023-10-31
191,1050545,C0000009481,Not required,C0000010388,500000027058,2023-10-31
192,1050587,C0000009478,Not required,C0000010385,500000027059,2023-10-31
...,...,...,...,...,...,...
779,61034569,C0000005900,Not required,C0000010545,500000028912,2023-12-17
780,61034569,C0000005901,Not required,C0000010546,500000028912,2023-12-17
781,61034569,C0000005902,Not required,C0000010547,500000028912,2023-12-17
782,1053201,P11220265,Not required,Not required,500000028314,2023-11-27
783,1053201,P11270073,Not required,Not required,500000028314,2023-11-27

In [151]:
awtracking_concat = pd.concat([awtracking_col, nonawtracking_col])
awtracking_concat

NameError: name 'awtracking_col' is not defined

# 5 EXPORT OUTPUT

## 5.1 BOM

In [152]:
output_filename1 = 'MRP_BOM_master.xlsx'
output_path1 = os.path.join(folder_path, output_filename1)
BOMtree_transformed_layouted.to_excel(output_path1, index=False)

## 5.2 RECYCLE MATERIAL

In [153]:
output_filename2 = 'MRP_BOM_recycle.xlsx'
output_path2 = os.path.join(folder_path, output_filename2)
df_recycle.to_excel(output_path2, index=False)

## 5.3 BOM CHANGE QUANTITY

In [154]:
output_filename3 = 'MRP_BOM_consumptionchange.xlsx'
output_path3 = os.path.join(folder_path, output_filename3)
df_change_quantity.to_excel(output_path3, index=False)

## 5.4 AW TRACKING

In [446]:
output_filename4 = 'AWtracking.xlsx'
output_path4 = os.path.join(folder_path, output_filename4)
awtracking_concat.to_excel(output_path4, index=False)

## 5.5 RM BOM

In [232]:
output_filename5 = 'rmBOM.xlsx'
output_path5 = os.path.join(folder_path, output_filename5)
rmBOM.to_excel(output_path5, index=False)

## 5.6 PM BOM

In [233]:
output_filename6 = 'pmBOM.xlsx'
output_path6 = os.path.join(folder_path, output_filename6)
pmBOM.to_excel(output_path6, index=False)

In [234]:
print("DONE")

DONE