# CONFIG

In [102]:
user_email = 'danh_bui@colpal.com'
folder_path = 'O:\\Shared drives\\Supply Network Planning\\03. Master Data\\Master data  CSV file\\'
sku_csv_name = 'Master SKU .csv'

# KẾT NỐI SNOWFLAKE

In [ ]:
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas
import sys
import pandas as pd
con = snowflake.connector.connect(
    
)
cur = con.cursor()

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://sso.colpal.com/app/snowflake/exk5d2wdao1LeZ8Vr357/sso/saml?SAMLRequest=pZPBcpswFEV%2FhVHXIAF27WhsZ6hxUmZIjGPsabNTQHZUhEQlEZy%2Fr8BxJ10km%2B400r16570rza5PNXdeqNJMijnwPQQcKgpZMnGcg11%2B406Bow0RJeFS0Dl4pRpcL2aa1LzBUWuexQP93VJtHHuR0Hg4mINWCSyJZhoLUlONTYG30V2KAw%2FhRkkjC8nBO8vnDqI1VcYSXiylZhbv2ZgGQ9h1ndeFnlRHGCCEILqCVtVLvlz0J9vTB3ofolGvtworz97YvjFxHsFnWE9nkcbf8zxzs%2FU2B050QV1Koduaqi1VL6ygu4f0DKAtwXKd3kb5KovSu3Wa7Ffxau%2B12i2oMIpw3zsWjaeF7A6cVLSQddMaW8ezK3igJeTyyOwokngOmoqVYb0qCBlNUBxLub6vTPLriZiNqNDt5uvPNl%2Bewumm3TfVj10BnP0l66DPOtG6pYnoEzZ2CwWh6weuP879CQ4RRlNvdIUegRPbhJkgZnBe2tBaWibeED6gkaaBf6khPVXjMuhKIv2UPk73KhxPegfs4wbnF4SH8mrx%2F3OZwff3vT3Pe5tYEmeSs%2BLVuZGqJubjQH3PH3ZY6R4GKaY1YTwqS0W1tsFyLrulosTYX2BUSwFcnKv%2B%2Bw8WfwA%3D&RelayState=52724 to authenticate...

# TẠO BẢNG

In [123]:
# Create the table in Snowflake if it doesn't exist
table_name = 'MP3_MASTER_SKU'
query_create_table = f"""
    CREATE TABLE IF NOT EXISTS MP3_DATA.{table_name} (
        "DATE_CREATE_SKU" VARCHAR(60),
        "BRISTLE" VARCHAR(60),
        "MACHINE_TYPE" VARCHAR(60),
        "VN_SKU" VARCHAR(60),
        "SUB_SKU" VARCHAR(60),
        "MDGM_SKU" VARCHAR(60),
        "DIVISION_OWNER" VARCHAR(60),
        "LOADING_METHOD" VARCHAR(60),
        "BUNDLE_NAME" VARCHAR(60),
        "MP_SKU_DESCRIPTION" VARCHAR(60),
        "CASE_COUNT_PCS" NUMBER(7,2),
        "CBM" NUMBER(15,9),
        "PALLET_MP" NUMBER(7,2),
        "CURRENT_STATUS" VARCHAR(60),
        "REPLACE_FOR_SKU" VARCHAR(60),
        "CODE_DATE" VARCHAR(60),
        "SOURCING_SUBS" VARCHAR(600),
        "SHORT_BUNDLE_NAME" VARCHAR(60),
        "PROJECT_NAME" VARCHAR(60)
    )
"""

with con.cursor() as cursor:
    cursor.execute(query_create_table)

# XỬ LÝ DATA

In [115]:
df_sku = pd.read_csv(folder_path+sku_csv_name, skiprows=2, usecols=range(0,19))
df_sku.head()

,Date create SKU,Bristle,Machine Type,VN SKU,Sub SKU,MDGM SKU,Division (Owner),Loading Method,Bundle Name,MP SKU Description,Case Count (Pcs),CBM,Pallet MP,Current Status,Replace for SKU ( Old SKU#),CODE DATE,Sourcing subs,Short Bundle Name,Project name
0,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,S,1PK,1050301,1050301,VN00258A,Grt Asia,Floor loading,Premier Clean 14,CTBM CLASSIC_CLEAN FH S 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
1,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,Naked,1052134,1052134,VN00576A,Grt Asia,Floor loading,Premier Clean 14,CTBM EXTRA_CLEAN FH M NKBR ASIA*288,288.0,0.017085999999999997,68.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
2,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,Cello with Cap,1051806,155501,VN00554A,NaN,Slip sheet,Classic Pokey,CTBM CLASSIC POKEY LH S CLPK US*144,144.0,0.007649,136.0,Discontinued,NaN,Not required,NaN,CP_09,NaN
3,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,2PK,1052133,FVN63042,VN00340A,Latam,Slip sheet,Extra Clean 15,CTBM EXTRA_CLEAN FH M 2PK LATAM*24,24.0,0.004625,260.0,Discontinued,1052180,Not required,NaN,EC_15,NaN
4,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,1PK,1050413,1050413,VN00266A,Grt Asia,Floor loading,Super Shine,CTBM PREMIER CLEAN FH M 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,MFG DD/MM/YYYY \nEXP DD/MM/YYYY,NaN,NaN,NaN

In [116]:
df_sku.columns = [
    "DATE_CREATE_SKU",
    "BRISTLE",
    "MACHINE_TYPE",
    "VN_SKU",
    "SUB_SKU",
    "MDGM_SKU",
    "DIVISION_OWNER",
    "LOADING_METHOD",
    "BUNDLE_NAME",
    "MP_SKU_DESCRIPTION",
    "CASE_COUNT_PCS",
    "CBM",
    "PALLET_MP",
    "CURRENT_STATUS",
    "REPLACE_FOR_SKU",
    "CODE_DATE",
    "SOURCING_SUBS",
    "SHORT_BUNDLE_NAME",
    "PROJECT_NAME"
]
df_sku.head()

,DATE_CREATE_SKU,BRISTLE,MACHINE_TYPE,VN_SKU,SUB_SKU,MDGM_SKU,DIVISION_OWNER,LOADING_METHOD,BUNDLE_NAME,MP_SKU_DESCRIPTION,CASE_COUNT_PCS,CBM,PALLET_MP,CURRENT_STATUS,REPLACE_FOR_SKU,CODE_DATE,SOURCING_SUBS,SHORT_BUNDLE_NAME,PROJECT_NAME
0,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,S,1PK,1050301,1050301,VN00258A,Grt Asia,Floor loading,Premier Clean 14,CTBM CLASSIC_CLEAN FH S 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
1,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,Naked,1052134,1052134,VN00576A,Grt Asia,Floor loading,Premier Clean 14,CTBM EXTRA_CLEAN FH M NKBR ASIA*288,288.0,0.017085999999999997,68.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
2,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,Cello with Cap,1051806,155501,VN00554A,NaN,Slip sheet,Classic Pokey,CTBM CLASSIC POKEY LH S CLPK US*144,144.0,0.007649,136.0,Discontinued,NaN,Not required,NaN,CP_09,NaN
3,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,2PK,1052133,FVN63042,VN00340A,Latam,Slip sheet,Extra Clean 15,CTBM EXTRA_CLEAN FH M 2PK LATAM*24,24.0,0.004625,260.0,Discontinued,1052180,Not required,NaN,EC_15,NaN
4,Wed Oct 01 2008 00:00:00 GMT+0700 (Indochina T...,M,1PK,1050413,1050413,VN00266A,Grt Asia,Floor loading,Super Shine,CTBM PREMIER CLEAN FH M 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,MFG DD/MM/YYYY \nEXP DD/MM/YYYY,NaN,NaN,NaN

In [117]:
# Xóa dòng thừa, xóa dấu cách thừa nếu có
df_sku = df_sku.dropna(how='all')
df_sku = df_sku.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [118]:
# Xử lý các cột dạng số
df_sku['CASE_COUNT_PCS'] = pd.to_numeric(df_sku['CASE_COUNT_PCS'], errors='coerce')
df_sku['CBM'] = pd.to_numeric(df_sku['CBM'], errors='coerce')
df_sku['PALLET_MP'] = pd.to_numeric(df_sku['PALLET_MP'], errors='coerce')

In [119]:
# Xử lý column Date Create SKU
df_sku['DATE_CREATE_SKU'] = df_sku['DATE_CREATE_SKU'].str[4:15]
df_sku['DATE_CREATE_SKU'] = pd.to_datetime(df_sku['DATE_CREATE_SKU'], errors='coerce')
df_sku['DATE_CREATE_SKU'] = df_sku['DATE_CREATE_SKU'].dt.strftime('%Y-%m-%d')

In [120]:
df_sku

,DATE_CREATE_SKU,BRISTLE,MACHINE_TYPE,VN_SKU,SUB_SKU,MDGM_SKU,DIVISION_OWNER,LOADING_METHOD,BUNDLE_NAME,MP_SKU_DESCRIPTION,CASE_COUNT_PCS,CBM,PALLET_MP,CURRENT_STATUS,REPLACE_FOR_SKU,CODE_DATE,SOURCING_SUBS,SHORT_BUNDLE_NAME,PROJECT_NAME
0,2008-10-01,S,1PK,1050301,1050301,VN00258A,Grt Asia,Floor loading,Premier Clean 14,CTBM CLASSIC_CLEAN FH S 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
1,2008-10-01,M,Naked,1052134,1052134,VN00576A,Grt Asia,Floor loading,Premier Clean 14,CTBM EXTRA_CLEAN FH M NKBR ASIA*288,288.0,0.017086,68.0,Discontinued,NaN,Not required,NaN,PC_14,NaN
2,2008-10-01,M,Cello with Cap,1051806,155501,VN00554A,NaN,Slip sheet,Classic Pokey,CTBM CLASSIC POKEY LH S CLPK US*144,144.0,0.007649,136.0,Discontinued,NaN,Not required,NaN,CP_09,NaN
3,2008-10-01,M,2PK,1052133,FVN63042,VN00340A,Latam,Slip sheet,Extra Clean 15,CTBM EXTRA_CLEAN FH M 2PK LATAM*24,24.0,0.004625,260.0,Discontinued,1052180,Not required,NaN,EC_15,NaN
4,2008-10-01,M,1PK,1050413,1050413,VN00266A,Grt Asia,Floor loading,Super Shine,CTBM PREMIER CLEAN FH M 1PK ASIA*72,72.0,0.020753,60.0,Discontinued,NaN,MFG DD/MM/YYYY \nEXP DD/MM/YYYY,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,2023-08-14,M,NaN,61041843,61041843,61041843,Europe,Slip sheet,Procuidado colors 22,CTBM TWISTER Colors 3PK_EU,36.0,0.005645,168.0,New,NaN,Not required,NaN,PRO_22CH,NaN
1289,2023-08-18,Head plate,Head plate,61038552,61038552,61038552,Grt Asia,Floor loading,NaN,CTBM 360 Optic White FH Headplate,2448.0,0.054889,8.0,New,NaN,Not required,NaN,NaN,NaN
1290,2023-10-30,M,NaN,61043787,61043787,61043787,Grt Asia,Floor loading,Premier Clean 22,CTBM Deluxe Plus 1pk TH*72,72.0,0.019288,60.0,New,NaN,MFG DD/MM/YYYY \nEXP DD/MM/YYYY,NaN,PC_22,NaN
1291,2023-11-29,S,6pin,61044434,61044434,61044434,Grt Asia,Floor loading,Extra Clean 22 rPP,CTBM Extra Clean 1pk 10+2 TH*72,72.0,NaN,NaN,New,NaN,MFG DD/MM/YYYY \nEXP DD/MM/YYYY,NaN,EC_22RPP,NaN
1292,2023-12-01,S,NaN,61044463,61044463,61044463,Grt Asia,Floor loading,SlimSoft charcoal 19,CTBM SS In Between Charcoal HGER VNx144,NaN,NaN,NaN,New,NaN,NaN,NaN,SSCC_19,NaN

# Đẩy dữ liệu lên (dạng replace data cũ)

In [128]:
# Upload với tùy chọn replace
success, nchunks, nrows, _ = write_pandas(con, df_sku, table_name, overwrite=True, quote_identifiers=False)
print('Done')

C:\Users\Danh Bui\AppData\Local\Temp\ipykernel_6324\2797126900.py:2: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.numeric.Int64Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  success, nchunks, nrows, _ = write_pandas(con, df_sku, table_name, overwrite=True, quote_identifiers=False)

Done